"""
Fixtures API Routes
====================
All routes in this module read ONLY from the local PostgreSQL database.
No external API calls are made.  Data is kept fresh by the background
``task_sync_matches`` Celery task which runs every 5 minutes.

Endpoints
---------
GET /fixtures/upcoming              – upcoming matches (+ predictions)
GET /fixtures/today                 – today's matches
GET /fixtures/results               – finished matches with scores (?days=7)
GET /fixtures/results/weekly-summary – weekly winners/losers stats

SIMULATION / EDUCATIONAL DISCLAIMER
-------------------------------------
All probability estimates provided on this platform are produced by a
statistical model for simulation and educational research purposes only.
They do NOT constitute financial, betting, or investment advice of any kind.
"""
from __future__ import annotations

import uuid
from datetime import date, datetime, timedelta, timezone
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Depends, HTTPException, Query, status
from pydantic import BaseModel, ConfigDict, Field
from sqlalchemy import and_, or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth.tier import get_current_tier
from app.core.prediction_filters import trackrecord_filter
from app.core.tier_leagues import (
    LEAGUES_FREE,
    LEAGUES_GOLD,
    LEAGUES_PLATINUM,
    LEAGUES_SILVER,
)
from app.core.tier_system import (
    CONF_THRESHOLD,
    PickTier,
    TIER_METADATA,
    TIER_SYSTEM_ENABLED,
    pick_tier_expression,
    tier_info,
)
from app.db.session import get_db
from app.models.league import League
from app.models.match import Match, MatchResult, MatchStatus
from app.models.prediction import Prediction
from app.models.team import Team

router = APIRouter()


def _classify_pick_tier(league_id: Any, confidence: float) -> Optional[PickTier]:
    """Python mirror of ``pick_tier_expression`` SQL CASE.

    Returns the highest tier the prediction qualifies for, or ``None``
    if it falls below every tier's threshold (conf < 0.55 or league
    outside LEAGUES_FREE). Same ordering rule as the SQL side —
    Platinum is checked first, then Gold, Silver, Free.
    """
    league_str = str(league_id)
    if league_str in LEAGUES_PLATINUM and confidence >= CONF_THRESHOLD[PickTier.PLATINUM]:
        return PickTier.PLATINUM
    if league_str in LEAGUES_GOLD and confidence >= CONF_THRESHOLD[PickTier.GOLD]:
        return PickTier.GOLD
    if league_str in LEAGUES_SILVER and confidence >= CONF_THRESHOLD[PickTier.SILVER]:
        return PickTier.SILVER
    if league_str in LEAGUES_FREE and confidence >= CONF_THRESHOLD[PickTier.FREE]:
        return PickTier.FREE
    return None

_SIMULATION_DISCLAIMER = (
    "SIMULATION / EDUCATIONAL USE ONLY. "
    "All probability estimates are generated by a statistical model for "
    "research and educational purposes. They do NOT constitute financial, "
    "betting, or investment advice. Past model performance is not indicative "
    "of future results. Always gamble responsibly and within applicable laws."
)


# ─────────────────────────────────────────────────────────────────────────────
# Response schemas
# ─────────────────────────────────────────────────────────────────────────────


class PredictionSummary(BaseModel):
    """Rich prediction summary embedded in a fixture response.

    Only returned when the pick is visible to the caller. When the
    pick's tier is above the caller's subscription tier, the parent
    FixtureItem drops this field and instead sets ``locked_pick_tier``
    so the UI can render an upgrade teaser in its place.
    """

    model_config = ConfigDict(from_attributes=True)

    id: str
    home_win_prob: float
    draw_prob: Optional[float] = None
    away_win_prob: float
    predicted_home_score: Optional[float] = None
    predicted_away_score: Optional[float] = None
    confidence: float
    model_name: Optional[str] = None
    predicted_at: Optional[str] = None
    pick: Optional[str] = None  # HOME / DRAW / AWAY
    reasoning: Optional[str] = None
    edge: Optional[Dict[str, float]] = None  # {home: 0.04, draw: -0.02, away: -0.02}
    implied_probabilities: Optional[Dict[str, float]] = None
    top_features: Optional[List[Dict[str, Any]]] = None
    # v8.2 — ranked top-3 human-readable drivers derived from
    # features_snapshot. Populated on fixture list + detail so the
    # /predictions list view can render "Why this pick?" inline.
    top_drivers: Optional[List[Dict[str, Any]]] = None
    strategies_matched: Optional[List[str]] = None
    # v8.3 — pick-tier metadata shown as the badge on the visible pick.
    pick_tier: Optional[str] = None
    pick_tier_label: Optional[str] = None
    pick_tier_accuracy: Optional[str] = None
    disclaimer: str = _SIMULATION_DISCLAIMER
    is_simulation: bool = True


class ResultSummary(BaseModel):
    """Score summary embedded in a fixture response."""

    home_score: int
    away_score: int
    home_score_ht: Optional[int] = None
    away_score_ht: Optional[int] = None
    winner: Optional[str] = None  # "home" | "away" | "draw"


class OddsSummary(BaseModel):
    """v6: pre-match odds embedded in a fixture response.

    Only populated when an ``odds_history`` row exists for the match.
    When no odds are on file, the ``odds`` field on FixtureItem is
    left as None and the frontend should render nothing — NOT a "—"
    placeholder. See docs/v6_bugfix_report.md §B1.
    """

    home: Optional[float] = None
    draw: Optional[float] = None
    away: Optional[float] = None
    over_2_5: Optional[float] = None
    under_2_5: Optional[float] = None
    bookmaker: Optional[str] = None
    fetched_at: Optional[str] = None


class FixtureItem(BaseModel):
    """A single fixture row as returned by the /fixtures endpoints."""

    id: str
    league_id: str
    league_name: Optional[str] = None
    league_slug: Optional[str] = None
    league_country: Optional[str] = None
    home_team_id: str
    home_team_name: Optional[str] = None
    home_team_slug: Optional[str] = None
    home_team_logo: Optional[str] = None
    away_team_id: str
    away_team_name: Optional[str] = None
    away_team_slug: Optional[str] = None
    away_team_logo: Optional[str] = None
    external_id: Optional[str] = None
    status: str
    scheduled_at: datetime
    venue: Optional[str] = None
    round_name: Optional[str] = None
    matchday: Optional[int] = None
    result: Optional[ResultSummary] = None
    prediction: Optional[PredictionSummary] = None
    odds: Optional[OddsSummary] = None
    # v8.4 — set when a v8.1 prediction EXISTS for this match but the
    # caller's tier is below the pick's tier. The prediction field is
    # then null and the UI renders an upgrade teaser using these slugs.
    locked_pick_tier: Optional[str] = None
    locked_pick_tier_label: Optional[str] = None
    locked_pick_tier_accuracy: Optional[str] = None
    # v6.3: real-time live score — only set for matches with status=LIVE
    # Populated from Redis cache, refreshed every 60s via API-Football.
    live_score: Optional[dict] = None


class UpcomingFixturesResponse(BaseModel):
    """Response envelope for /fixtures/upcoming."""

    count: int
    disclaimer: str = _SIMULATION_DISCLAIMER
    fixtures: List[FixtureItem]


class TodayFixturesResponse(BaseModel):
    """Response envelope for /fixtures/today."""

    date: str
    count: int
    disclaimer: str = _SIMULATION_DISCLAIMER
    fixtures: List[FixtureItem]


class ResultsResponse(BaseModel):
    """Response envelope for /fixtures/results."""

    days: int
    count: int
    disclaimer: str = _SIMULATION_DISCLAIMER
    fixtures: List[FixtureItem]


class WeeklySummaryItem(BaseModel):
    """One team's performance entry in the weekly summary."""

    team_id: str
    team_name: Optional[str]
    team_slug: Optional[str]
    matches_played: int
    wins: int
    draws: int
    losses: int
    goals_for: int
    goals_against: int
    goal_difference: int
    points: int


class WeeklyPerformer(BaseModel):
    name: str
    accuracy: float
    total: int


class WeeklySummaryResponse(BaseModel):
    """Response matching frontend WeeklySummary type."""

    total_calls: int = 0
    won: int = 0
    lost: int = 0
    win_rate: float = 0.0
    pl_units: float = 0.0
    best_performers: List[WeeklyPerformer] = []
    worst_performers: List[WeeklyPerformer] = []
    disclaimer: str = _SIMULATION_DISCLAIMER


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────


async def _load_latest_odds(
    match_ids: list,
    db: AsyncSession,
) -> dict:
    """v6: return ``{match_id: OddsSummary}`` mapping for the most
    recent 1x2 odds row per match. Also looks up over/under 2.5
    odds from the same table and merges them into a single summary.
    """
    if not match_ids:
        return {}

    from app.models.odds import OddsHistory

    # 1x2 rows per match — pick the most recent recorded_at
    from sqlalchemy import func as sfunc

    subq_1x2 = (
        select(
            OddsHistory.match_id,
            sfunc.max(OddsHistory.recorded_at).label("latest_at"),
        )
        .where(
            and_(
                OddsHistory.match_id.in_(match_ids),
                OddsHistory.market.in_(["1x2", "1X2"]),
            )
        )
        .group_by(OddsHistory.match_id)
        .subquery()
    )
    stmt_1x2 = (
        select(OddsHistory)
        .join(
            subq_1x2,
            and_(
                OddsHistory.match_id == subq_1x2.c.match_id,
                OddsHistory.recorded_at == subq_1x2.c.latest_at,
                OddsHistory.market.in_(["1x2", "1X2"]),
            ),
        )
    )
    rows_1x2 = (await db.execute(stmt_1x2)).scalars().all()

    # Over/Under 2.5 rows per match
    subq_ou = (
        select(
            OddsHistory.match_id,
            sfunc.max(OddsHistory.recorded_at).label("latest_at"),
        )
        .where(
            and_(
                OddsHistory.match_id.in_(match_ids),
                OddsHistory.market == "over_under_2_5",
            )
        )
        .group_by(OddsHistory.match_id)
        .subquery()
    )
    stmt_ou = (
        select(OddsHistory)
        .join(
            subq_ou,
            and_(
                OddsHistory.match_id == subq_ou.c.match_id,
                OddsHistory.recorded_at == subq_ou.c.latest_at,
                OddsHistory.market == "over_under_2_5",
            ),
        )
    )
    rows_ou = (await db.execute(stmt_ou)).scalars().all()
    ou_by_match = {r.match_id: r for r in rows_ou}

    result: dict = {}
    for row in rows_1x2:
        ou_row = ou_by_match.get(row.match_id)
        result[row.match_id] = OddsSummary(
            home=row.home_odds,
            draw=row.draw_odds,
            away=row.away_odds,
            over_2_5=(ou_row.over_odds if ou_row else None),
            under_2_5=(ou_row.under_odds if ou_row else None),
            bookmaker=row.source,
            fetched_at=row.recorded_at.isoformat() if row.recorded_at else None,
        )

    # Also include matches that only have O/U rows but no 1x2 — rare
    # but possible during the snapshot accumulation period.
    for mid, ou_row in ou_by_match.items():
        if mid not in result:
            result[mid] = OddsSummary(
                over_2_5=ou_row.over_odds,
                under_2_5=ou_row.under_odds,
                bookmaker=ou_row.source,
                fetched_at=ou_row.recorded_at.isoformat() if ou_row.recorded_at else None,
            )

    return result


def _build_fixture_item(
    match: Match,
    latest_prediction: Optional[Prediction] = None,
    odds: Optional[OddsSummary] = None,
    user_tier: Optional[PickTier] = None,
) -> FixtureItem:
    """Convert a Match ORM object to a FixtureItem response schema.

    When ``user_tier`` is provided and the latest prediction's pick-tier
    exceeds that, the returned PredictionSummary has ``locked=True`` and
    all sensitive fields (probs, confidence, pick, reasoning) are nulled.
    The tier badge metadata stays so the UI can render an upgrade teaser.
    """
    result_summary: Optional[ResultSummary] = None
    if match.result:
        result_summary = ResultSummary(
            home_score=match.result.home_score,
            away_score=match.result.away_score,
            home_score_ht=match.result.home_score_ht,
            away_score_ht=match.result.away_score_ht,
            winner=match.result.winner,
        )

    pred_summary: Optional[PredictionSummary] = None
    locked_meta: tuple = (None, None, None)
    if latest_prediction:
        model_name = None
        if latest_prediction.model_version:
            model_name = latest_prediction.model_version.name

        # Determine pick
        probs = {
            "HOME": latest_prediction.home_win_prob,
            "DRAW": latest_prediction.draw_prob or 0,
            "AWAY": latest_prediction.away_win_prob,
        }
        pick = max(probs, key=lambda k: probs[k])

        # Generate reasoning from explanation if available
        reasoning = None
        if latest_prediction.explanation:
            reasoning = latest_prediction.explanation.summary
        else:
            # Template-based reasoning
            home_name = match.home_team.name if match.home_team else "Home"
            away_name = match.away_team.name if match.away_team else "Away"
            if pick == "HOME":
                reasoning = f"{home_name} favored with {latest_prediction.home_win_prob:.0%} win probability. Confidence: {latest_prediction.confidence:.0%}."
            elif pick == "AWAY":
                reasoning = f"{away_name} favored with {latest_prediction.away_win_prob:.0%} win probability. Confidence: {latest_prediction.confidence:.0%}."
            else:
                reasoning = f"Draw most likely at {(latest_prediction.draw_prob or 0):.0%}. Confidence: {latest_prediction.confidence:.0%}."

        # Edge vs uniform market (33% baseline)
        edge = {
            "home": round(latest_prediction.home_win_prob - 1/3, 4),
            "draw": round((latest_prediction.draw_prob or 0) - 1/3, 4),
            "away": round(latest_prediction.away_win_prob - 1/3, 4),
        }

        # Top features from raw_output
        top_features = None
        if latest_prediction.raw_output and isinstance(latest_prediction.raw_output, dict):
            sub_models = latest_prediction.raw_output.get("sub_models", [])
            features_list = []
            for sm in sub_models:
                if "error" not in sm:
                    features_list.append({
                        "name": sm.get("model", "Unknown"),
                        "home": round(sm.get("home_win_prob", 0), 4),
                        "draw": round(sm.get("draw_prob", 0), 4),
                        "away": round(sm.get("away_win_prob", 0), 4),
                        "weight": round(sm.get("weight", 0), 2),
                    })
            if features_list:
                top_features = features_list

        # v8.2: top-3 feature drivers for the inline reasoning block.
        from app.services.pick_drivers import compute_top_drivers
        top_drivers = compute_top_drivers(
            getattr(latest_prediction, "features_snapshot", None)
        )

        # v8.4 — classify the pick's tier and compare to the caller's
        # tier. If the pick is above the user's tier we emit a lock
        # marker on the FixtureItem itself (see locked_meta below) and
        # skip the full PredictionSummary so sensitive probs/pick are
        # never serialised.
        pick_tier_enum = _classify_pick_tier(
            match.league_id, latest_prediction.confidence or 0.0
        )
        meta: Dict[str, Optional[str]] = {
            "pick_tier": None,
            "pick_tier_label": None,
            "pick_tier_accuracy": None,
        }
        if pick_tier_enum is not None:
            meta = tier_info(pick_tier_enum)

        # Only lock picks for matches that haven't finished yet — once a
        # match is settled the pick is public history (it shows on
        # /trackrecord and feeds /trackrecord/live-measurement). Hiding
        # finished Platinum/Gold picks from lower-tier callers also
        # broke the public what-if calculator on /results, which needs
        # the prediction body to simulate payouts per tier.
        is_finished = match.status == MatchStatus.FINISHED or (
            isinstance(match.status, str) and match.status == "finished"
        )
        is_locked = (
            TIER_SYSTEM_ENABLED
            and user_tier is not None
            and pick_tier_enum is not None
            and int(pick_tier_enum) > int(user_tier)
            and not is_finished
        )

        if is_locked:
            pred_summary = None
            locked_meta = (
                meta["pick_tier"],
                meta["pick_tier_label"],
                meta["pick_tier_accuracy"],
            )
        else:
            pred_summary = PredictionSummary(
                id=str(latest_prediction.id),
                home_win_prob=latest_prediction.home_win_prob,
                draw_prob=latest_prediction.draw_prob,
                away_win_prob=latest_prediction.away_win_prob,
                predicted_home_score=latest_prediction.predicted_home_score,
                predicted_away_score=latest_prediction.predicted_away_score,
                confidence=latest_prediction.confidence,
                model_name=model_name,
                predicted_at=latest_prediction.predicted_at.isoformat()
                if latest_prediction.predicted_at else None,
                pick=pick,
                reasoning=reasoning,
                edge=edge,
                top_features=top_features,
                top_drivers=top_drivers,
                pick_tier=meta["pick_tier"],
                pick_tier_label=meta["pick_tier_label"],
                pick_tier_accuracy=meta["pick_tier_accuracy"],
            )
            locked_meta = (None, None, None)

    return FixtureItem(
        id=str(match.id),
        league_id=str(match.league_id),
        league_name=match.league.name if match.league else None,
        league_slug=match.league.slug if match.league else None,
        league_country=match.league.country if match.league else None,
        home_team_id=str(match.home_team_id),
        home_team_name=match.home_team.name if match.home_team else None,
        home_team_slug=match.home_team.slug if match.home_team else None,
        home_team_logo=match.home_team.logo_url if match.home_team else None,
        away_team_id=str(match.away_team_id),
        away_team_name=match.away_team.name if match.away_team else None,
        away_team_slug=match.away_team.slug if match.away_team else None,
        away_team_logo=match.away_team.logo_url if match.away_team else None,
        external_id=match.external_id,
        status=match.status.value if isinstance(match.status, MatchStatus) else str(match.status),
        scheduled_at=match.scheduled_at,
        venue=match.venue,
        round_name=match.round_name,
        matchday=match.matchday,
        result=result_summary,
        prediction=pred_summary,
        locked_pick_tier=locked_meta[0],
        locked_pick_tier_label=locked_meta[1],
        locked_pick_tier_accuracy=locked_meta[2],
        odds=odds,
    )


async def _enrich_with_live_scores(items: List[FixtureItem], matches: list) -> None:
    """Attach cached live-score data (including elapsed minute) to any
    LIVE fixture in ``items``.

    The Redis cache ``live:fixtures`` is populated every ~60s by
    ``job_sync_live_fixtures`` in the background scheduler — all callers
    share the same cache, so this adds no API-Football load.

    Mutates ``items`` in-place. Safe to call on empty lists.
    """
    if not items:
        return
    # Only bother if at least one fixture is live.
    live_items = [it for it in items if (it.status or "").lower() == "live"]
    if not live_items:
        return

    try:
        from app.core.cache import cache_get  # local import to avoid circular deps
        cached = await cache_get("live:fixtures") or []
    except Exception:  # noqa: BLE001 — cache read must never break the response
        return

    if not cached:
        return

    score_by_afid: dict[str, dict] = {}
    for entry in cached:
        afid = str(entry.get("api_football_id", ""))
        if afid:
            score_by_afid[afid] = entry

    by_match_id = {str(m.id): m for m in matches}

    for item in live_items:
        match = by_match_id.get(str(item.id))
        if not match or not match.external_id:
            continue
        if not match.external_id.startswith("apifb_match_"):
            continue
        afid = match.external_id.replace("apifb_match_", "")
        hit = score_by_afid.get(afid)
        if not hit:
            continue
        item.live_score = {
            "home_goals": hit.get("home_goals"),
            "away_goals": hit.get("away_goals"),
            "elapsed": hit.get("elapsed"),
            "status": hit.get("status"),
            "halftime_home": hit.get("halftime_home"),
            "halftime_away": hit.get("halftime_away"),
        }


async def _load_latest_predictions(
    match_ids: list,
    db: AsyncSession,
    user_tier: Optional[PickTier] = None,
) -> dict:
    """Return a {match_id: Prediction} mapping for the latest prediction per match.

    When ``TIER_SYSTEM_ENABLED`` and ``user_tier`` is provided, the latest
    prediction must also pass :func:`access_filter` and
    :func:`v81_predictions_filter` — matches whose only prediction is
    gated above the user's tier are excluded from the returned dict so
    the caller can drop them from the response.
    """
    if not match_ids:
        return {}

    # Subquery: max predicted_at per match_id, but scoped to v8.1
    # predictions only. Without v81_predictions_filter() here we'd pick
    # the absolute latest row — which may be a pre-v8.1 backtest — and
    # then drop the whole match when the outer v81 filter rejects it,
    # even when an older but valid v8.1 prediction still exists. That
    # caused the PotD/match-detail divergence (PotD found a prediction,
    # detail page showed "No forecast yet") because BOTD filters v8.1
    # BEFORE sorting and we didn't.
    from sqlalchemy import func
    subq_base = select(
        Prediction.match_id,
        func.max(Prediction.predicted_at).label("latest_at"),
    )
    if TIER_SYSTEM_ENABLED:
        # Join Match inside the subquery so trackrecord_filter() (which
        # references Match.scheduled_at to exclude post-kickoff rows)
        # has its operand in scope. Without the join the filter raises
        # at query-planning time.
        subq_base = subq_base.join(Match, Match.id == Prediction.match_id).where(
            trackrecord_filter(),
            Prediction.match_id.in_(match_ids),
        )
    else:
        subq_base = subq_base.where(Prediction.match_id.in_(match_ids))
    subq = subq_base.group_by(Prediction.match_id).subquery()

    from sqlalchemy.orm import noload

    # model_version already uses lazy="selectin" on the ORM model,
    # so no explicit selectinload needed.  Suppress evaluation loading
    # since we only need model_version and explanation here.
    stmt = (
        select(Prediction)
        .options(noload(Prediction.evaluation))
        .join(
            subq,
            and_(
                Prediction.match_id == subq.c.match_id,
                Prediction.predicted_at == subq.c.latest_at,
            ),
        )
    )
    # v8.4 — return ALL latest v8.1 predictions regardless of the
    # caller's tier. The ``user_tier`` is still accepted (for call
    # sites that haven't been updated) but the access gate is now
    # enforced in ``_build_fixture_item`` by masking sensitive
    # fields on picks that exceed the user's tier. That way the
    # fixture list keeps showing every match + prediction pair
    # (with a locked teaser badge for above-tier picks) instead of
    # silently dropping them — which to the user reads as "no
    # prediction" and breaks trust.
    # v8.4 follow-up (P2-C): keep the tier funnel intact by requiring
    # the match league to be in LEAGUES_FREE. Without this we'd leak
    # predictions from non-top-14 leagues (A-League, Serie B, etc.)
    # to anonymous callers with no tier classification — picks that
    # were never part of any paid tier's scope per tier_system_plan.md.
    if TIER_SYSTEM_ENABLED:
        stmt = (
            stmt
            .join(Match, Match.id == Prediction.match_id)
            .where(Match.league_id.in_(LEAGUES_FREE))
            .where(trackrecord_filter())
        )
    rows = (await db.execute(stmt)).scalars().all()
    return {p.match_id: p for p in rows}


# ─────────────────────────────────────────────────────────────────────────────
# Dedup helper — filter out API-Football duplicates
# ─────────────────────────────────────────────────────────────────────────────
#
# The database contains fixtures from two sources:
#   1. football-data.org (external_id like "fd_org_..." or NULL) — ongoing sync
#   2. API-Football (external_id like "apifb_match_...") — one-time batch import
#
# Both created the same matches with slightly different team names
# (e.g. "Toulouse" vs "Toulouse FC"). This dedup function keeps only the
# football-data.org version when a duplicate exists, by matching on
# (league_id, scheduled_at within 2h). The apifb fixture is hidden, not
# deleted, so predictions linked to it are unaffected.


def _dedup_fixtures(matches: list) -> list:
    """Remove API-Football duplicates when a football-data.org version exists."""
    # Group by (league_id, rounded scheduled_at to nearest 2h)
    seen: dict[tuple, object] = {}  # (league_id, time_bucket) → first match
    result = []

    for m in matches:
        eid = m.external_id or ""
        # Time bucket: round to nearest 2 hours to catch ±1h scheduling diffs
        bucket = None
        if m.scheduled_at:
            ts = m.scheduled_at.timestamp()
            bucket = int(ts // 7200)  # 7200s = 2h
        key = (str(m.league_id), bucket)

        if key in seen:
            existing = seen[key]
            existing_eid = existing.external_id or ""
            # If the existing one is apifb and current one is NOT apifb,
            # replace existing with the non-apifb (prefer fd_org).
            if existing_eid.startswith("apifb_match_") and not eid.startswith("apifb_match_"):
                # Swap: remove existing from result, add current
                result = [r for r in result if r.id != existing.id]
                seen[key] = m
                result.append(m)
            elif not existing_eid.startswith("apifb_match_") and eid.startswith("apifb_match_"):
                # Current is apifb duplicate, skip it
                continue
            else:
                # Both same source or both apifb — keep both (no dupe)
                result.append(m)
        else:
            seen[key] = m
            result.append(m)

    return result


# ─────────────────────────────────────────────────────────────────────────────
# Routes
# ─────────────────────────────────────────────────────────────────────────────


@router.get(
    "/upcoming",
    response_model=UpcomingFixturesResponse,
    summary="Upcoming matches from the local DB with predictions",
    description=(
        "Returns all scheduled/upcoming matches stored in the database, "
        "enriched with the latest AI prediction where available.  "
        "Data is refreshed every 5 minutes by the background sync task.  "
        "No external API calls are made by this endpoint.\n\n"
        "**" + _SIMULATION_DISCLAIMER + "**"
    ),
)
async def get_upcoming_fixtures(
    days: int = Query(
        default=7,
        ge=1,
        le=30,
        description="How many days ahead to look for fixtures (1–30).",
    ),
    league_slug: Optional[str] = Query(
        default=None, description="Filter by league slug (e.g. 'premier-league')."
    ),
    db: AsyncSession = Depends(get_db),
    user_tier: PickTier = Depends(get_current_tier),
) -> UpcomingFixturesResponse:
    now = datetime.now(timezone.utc)
    cutoff = now + timedelta(days=days)

    # Upcoming = SCHEDULED only. Live matches belong on /fixtures/live so
    # the Komend tab on the predictions page only ever lists matches that
    # have not yet kicked off.
    stmt = (
        select(Match)
        .where(
            and_(
                Match.status == MatchStatus.SCHEDULED,
                Match.scheduled_at >= now,
                Match.scheduled_at <= cutoff,
            )
        )
        .order_by(Match.scheduled_at)
    )

    if league_slug:
        stmt = stmt.join(League, League.id == Match.league_id).where(
            League.slug == league_slug
        )

    raw_matches = (await db.execute(stmt)).scalars().all()
    matches = _dedup_fixtures(raw_matches)
    match_ids = [m.id for m in matches]
    # Load predictions but do NOT filter out matches that have no prediction.
    # Hiding the match itself (not just the prediction) leaves the page blank
    # when Celery hasn't caught up yet. Tier-gating applies to the prediction
    # field inside each fixture — the match row itself is always visible.
    pred_map = await _load_latest_predictions(match_ids, db, user_tier)
    odds_map = await _load_latest_odds(match_ids, db)

    fixtures = [
        _build_fixture_item(m, pred_map.get(m.id), odds_map.get(m.id), user_tier=user_tier)
        for m in matches
    ]
    await _enrich_with_live_scores(fixtures, matches)

    return UpcomingFixturesResponse(count=len(fixtures), fixtures=fixtures)


@router.get(
    "/live",
    summary="Live/in-play matches with real-time scores (v6.3)",
    description=(
        "Returns currently live matches with real-time scores. Data comes "
        "from a Redis cache that the background job refreshes every 60s "
        "via a single API-Football call. Safe to poll every 30 seconds — "
        "all users read the same cache, no extra API calls.\n\n"
        "The ``live_score`` field on each fixture contains the current "
        "score, elapsed minutes, and halftime score when available.\n\n"
        "**" + _SIMULATION_DISCLAIMER + "**"
    ),
)
async def get_live_fixtures(
    league_slug: Optional[str] = Query(
        default=None, description="Filter by league slug."
    ),
    db: AsyncSession = Depends(get_db),
    user_tier: PickTier = Depends(get_current_tier),
):
    """Live matches with real-time scores from Redis cache."""
    from app.core.cache import cache_get

    # ── 1. Read live score cache (populated by job_sync_live_fixtures) ──
    live_cache = await cache_get("live:fixtures") or []

    # ── 2. Match cache entries against DB rows ──────────────────────────
    # The live-cache scheduler only stamps status=LIVE on rows whose
    # external_id starts with `apifb_match_*`. football-data.org rows
    # (Champions League, Premier League, etc. — most fd_org sourced
    # leagues) never get their status bumped, so the naive
    # `Match.status == LIVE` query silently dropped them.
    #
    # Fix: union of three result sets:
    #   (a) DB matches with explicit status=LIVE (apifb-sourced).
    #   (b) DB matches with status=SCHEDULED whose team-name pair
    #       matches a cache entry — these are fd_org matches the
    #       scheduler couldn't update.
    #   (c) Cache-only entries with no DB match at all (rare, returned
    #       as lightweight items without prediction).

    # Build a quick (home_lower, away_lower) → cache lookup.
    def _norm(s: str) -> str:
        return (s or "").strip().lower()

    cache_by_team_pair: dict[tuple[str, str], dict] = {}
    for entry in live_cache:
        key = (_norm(entry.get("home_team", "")), _norm(entry.get("away_team", "")))
        if key[0] and key[1]:
            cache_by_team_pair[key] = entry

    # (a) status=LIVE in DB
    stmt_live = (
        select(Match)
        .where(Match.status == MatchStatus.LIVE)
        .order_by(Match.scheduled_at)
    )
    if league_slug:
        stmt_live = stmt_live.join(League, League.id == Match.league_id).where(
            League.slug == league_slug
        )

    # (b) SCHEDULED matches kicked off in the last 4h that may be live
    # but weren't bumped (fd_org rows). Window keeps the result tight.
    window_start = datetime.now(timezone.utc) - timedelta(hours=4)
    window_end = datetime.now(timezone.utc) + timedelta(minutes=30)
    stmt_recent = (
        select(Match)
        .where(
            and_(
                Match.status == MatchStatus.SCHEDULED,
                Match.scheduled_at >= window_start,
                Match.scheduled_at <= window_end,
            )
        )
        .order_by(Match.scheduled_at)
    )
    if league_slug:
        stmt_recent = stmt_recent.join(League, League.id == Match.league_id).where(
            League.slug == league_slug
        )

    raw_live = (await db.execute(stmt_live)).scalars().all()
    raw_recent = (await db.execute(stmt_recent)).scalars().all()

    # Filter (b) to rows that have a cache hit — i.e. they ARE live
    # right now even though their status row says SCHEDULED.
    matched_recent: list = []
    for m in raw_recent:
        home = _norm(m.home_team.name if m.home_team else "")
        away = _norm(m.away_team.name if m.away_team else "")
        if (home, away) in cache_by_team_pair:
            matched_recent.append(m)

    matches = _dedup_fixtures(list(raw_live) + matched_recent)
    match_ids = [m.id for m in matches]
    # Do NOT filter out live matches without predictions — show the match
    # regardless. Tier-gating applies only to the prediction field.
    pred_map = await _load_latest_predictions(match_ids, db, user_tier)
    odds_map = await _load_latest_odds(match_ids, db)

    # api_football_id → cache lookup (for apifb-sourced matches)
    live_score_map: dict[str, dict] = {}
    for entry in live_cache:
        afid = str(entry.get("api_football_id", ""))
        if afid:
            live_score_map[afid] = entry

    # ── 3. Build response, enriching each fixture with live_score ──────
    fixtures = []
    matched_team_pairs: set[tuple[str, str]] = set()
    for m in matches:
        item = _build_fixture_item(m, pred_map.get(m.id), odds_map.get(m.id), user_tier=user_tier)

        # Force status=live on the response so the frontend renders the
        # live UI even when the DB row still says SCHEDULED.
        item.status = "live"

        # Try cache lookup by api_football_id first (apifb rows), then
        # by team-name pair (fd_org rows).
        eid = m.external_id or ""
        cached = None
        if eid.startswith("apifb_match_"):
            cached = live_score_map.get(eid.replace("apifb_match_", ""))
        if cached is None:
            home = _norm(m.home_team.name if m.home_team else "")
            away = _norm(m.away_team.name if m.away_team else "")
            cached = cache_by_team_pair.get((home, away))
            if cached:
                matched_team_pairs.add((home, away))

        if cached:
            item.live_score = {
                "home_goals": cached.get("home_goals"),
                "away_goals": cached.get("away_goals"),
                "elapsed": cached.get("elapsed"),
                "status": cached.get("status"),
                "halftime_home": cached.get("halftime_home"),
                "halftime_away": cached.get("halftime_away"),
            }

        fixtures.append(item)

    return {"count": len(fixtures), "fixtures": fixtures, "disclaimer": _SIMULATION_DISCLAIMER}


@router.get(
    "/today",
    response_model=TodayFixturesResponse,
    summary="Today's matches from the local DB",
    description=(
        "Returns all matches scheduled for today (UTC), enriched with "
        "predictions.  Data is refreshed every 5 minutes.\n\n"
        "**" + _SIMULATION_DISCLAIMER + "**"
    ),
)
async def get_today_fixtures(
    db: AsyncSession = Depends(get_db),
    user_tier: PickTier = Depends(get_current_tier),
) -> TodayFixturesResponse:
    today = date.today()
    day_start = datetime(today.year, today.month, today.day, tzinfo=timezone.utc)
    day_end = day_start + timedelta(days=1)

    stmt = (
        select(Match)
        .where(
            and_(
                Match.scheduled_at >= day_start,
                Match.scheduled_at < day_end,
            )
        )
        .order_by(Match.scheduled_at)
    )
    raw_matches = (await db.execute(stmt)).scalars().all()
    matches = _dedup_fixtures(raw_matches)
    match_ids = [m.id for m in matches]
    # Do NOT filter out matches that have no prediction — show the match
    # regardless; tier-gating applies only to the prediction field.
    pred_map = await _load_latest_predictions(match_ids, db, user_tier)
    odds_map = await _load_latest_odds(match_ids, db)

    fixtures = [
        _build_fixture_item(m, pred_map.get(m.id), odds_map.get(m.id), user_tier=user_tier)
        for m in matches
    ]
    await _enrich_with_live_scores(fixtures, matches)

    return TodayFixturesResponse(
        date=today.isoformat(),
        count=len(fixtures),
        fixtures=fixtures,
    )


@router.get(
    "/results/weekly-summary",
    response_model=WeeklySummaryResponse,
    summary="Weekly winners/losers summary",
    description=(
        "Aggregates results from the last 7 days to rank teams by points "
        "earned in that period.  Returns the top 5 and bottom 5 performers."
    ),
)
async def get_weekly_summary(
    days: int = Query(default=7, ge=1, le=90, description="Look-back window in days"),
    pick_tier: Optional[str] = Query(
        default=None,
        description=(
            "Optional public tier filter: 'free' | 'silver' | 'gold' | 'platinum'. "
            "Scopes the counted predictions to that exact pick-tier so dashboard "
            "widgets can show numbers consistent with a user's actual access."
        ),
    ),
    db: AsyncSession = Depends(get_db),
) -> WeeklySummaryResponse:
    """Prediction performance summary for the given look-back window."""
    from app.models.prediction import Prediction, PredictionEvaluation
    from app.api.routes.trackrecord import _parse_public_pick_tier

    now = datetime.now(timezone.utc)
    week_ago = now - timedelta(days=days)
    public_tier = _parse_public_pick_tier(pick_tier)

    # Get all evaluated predictions from last 7 days
    stmt = (
        select(Prediction, PredictionEvaluation)
        .join(Match, Match.id == Prediction.match_id)
        .join(PredictionEvaluation, PredictionEvaluation.prediction_id == Prediction.id)
        .where(
            and_(
                Match.scheduled_at >= week_ago,
                Match.scheduled_at <= now,
                Match.status == MatchStatus.FINISHED,
            )
        )
        .where(trackrecord_filter())
    )
    if TIER_SYSTEM_ENABLED and public_tier is not None:
        stmt = stmt.where(pick_tier_expression() == public_tier.value)
    rows = (await db.execute(stmt)).all()

    total_calls = len(rows)
    won = sum(1 for _, ev in rows if ev.is_correct)
    lost = total_calls - won
    win_rate = won / total_calls if total_calls > 0 else 0.0
    # P/L: flat staking 1 unit, assume avg odds ~1.9 for wins
    pl_units = (won * 0.9) - (lost * 1.0) if total_calls > 0 else 0.0

    # Best/worst by league
    league_stats: dict[str, dict] = {}
    for pred, ev in rows:
        league = pred.match.league.name if pred.match and pred.match.league else "Unknown"
        if league not in league_stats:
            league_stats[league] = {"name": league, "correct": 0, "total": 0}
        league_stats[league]["total"] += 1
        if ev.is_correct:
            league_stats[league]["correct"] += 1

    for s in league_stats.values():
        s["accuracy"] = s["correct"] / s["total"] if s["total"] > 0 else 0.0

    sorted_leagues = sorted(league_stats.values(), key=lambda x: x["accuracy"], reverse=True)
    best = [WeeklyPerformer(name=s["name"], accuracy=s["accuracy"], total=s["total"]) for s in sorted_leagues[:3]]
    worst = [WeeklyPerformer(name=s["name"], accuracy=s["accuracy"], total=s["total"]) for s in sorted_leagues[-3:]] if len(sorted_leagues) > 3 else []

    return WeeklySummaryResponse(
        total_calls=total_calls,
        won=won,
        lost=lost,
        win_rate=round(win_rate, 4),
        pl_units=round(pl_units, 2),
        best_performers=best,
        worst_performers=worst,
    )


@router.get(
    "/results",
    response_model=ResultsResponse,
    summary="Recent finished matches with scores and prediction evaluation",
    description=(
        "Returns finished matches from the last N days (default 7), "
        "including final scores and the latest model prediction for each "
        "match so accuracy can be assessed.  Data is refreshed continuously "
        "by the background sync tasks.\n\n"
        "**" + _SIMULATION_DISCLAIMER + "**"
    ),
)
async def get_results(
    days: int = Query(
        default=7,
        ge=1,
        le=365,
        description="How many days back to retrieve results (1–365).",
    ),
    league_slug: Optional[str] = Query(
        default=None, description="Filter by league slug."
    ),
    db: AsyncSession = Depends(get_db),
    user_tier: PickTier = Depends(get_current_tier),
) -> ResultsResponse:
    now = datetime.now(timezone.utc)
    cutoff = now - timedelta(days=days)

    stmt = (
        select(Match)
        .where(
            and_(
                Match.status == MatchStatus.FINISHED,
                Match.scheduled_at >= cutoff,
                Match.scheduled_at <= now,
            )
        )
        .order_by(Match.scheduled_at.desc())
    )

    if league_slug:
        stmt = stmt.join(League, League.id == Match.league_id).where(
            League.slug == league_slug
        )

    raw_matches = (await db.execute(stmt)).scalars().all()
    matches = _dedup_fixtures(raw_matches)
    match_ids = [m.id for m in matches]
    # Do NOT filter out matches without predictions — results should show all
    # finished matches. Tier-gating applies only to the prediction column.
    pred_map = await _load_latest_predictions(match_ids, db, user_tier)
    odds_map = await _load_latest_odds(match_ids, db)

    fixtures = [
        _build_fixture_item(m, pred_map.get(m.id), odds_map.get(m.id), user_tier=user_tier)
        for m in matches
    ]

    return ResultsResponse(days=days, count=len(fixtures), fixtures=fixtures)


# ─────────────────────────────────────────────────────────────────────────────
# Single-fixture detail + analysis
#
# These power the /matches/[id] detail page in the authed dashboard. They
# return the SAME FixtureItem shape the list endpoints use, plus a simple
# pre-match analysis summary (last-5 form per team, H2H aggregate). No
# coupling to the broken /matches/{id} legacy schema.
# ─────────────────────────────────────────────────────────────────────────────


class TeamFormSummary(BaseModel):
    """Per-team recent-form stats. Mirrors the frontend TeamForm type."""

    last_5: List[str] = Field(
        default_factory=list,
        description="Most-recent-first list of 'W'/'D'/'L' codes for the last 5 finished matches.",
    )
    last_10: List[str] = Field(default_factory=list)
    wins: int = 0
    draws: int = 0
    losses: int = 0
    goals_scored: int = 0
    goals_conceded: int = 0


class HeadToHeadSummary(BaseModel):
    """Aggregated head-to-head history between two teams."""

    total: int = 0
    home_wins: int = 0
    draws: int = 0
    away_wins: int = 0
    summary: Optional[str] = None


class FixtureAnalysisResponse(BaseModel):
    """Pre-match analysis: core fixture + form per team + H2H aggregate."""

    match: FixtureItem
    home_team_form: TeamFormSummary
    away_team_form: TeamFormSummary
    head_to_head: HeadToHeadSummary


async def _team_form_summary(
    team_id: uuid.UUID, db: AsyncSession, window: int = 10
) -> TeamFormSummary:
    """Compute W/D/L codes + goal totals for a team's most recent finished games."""
    stmt = (
        select(Match)
        .where(
            or_(Match.home_team_id == team_id, Match.away_team_id == team_id),
            Match.status == MatchStatus.FINISHED,
        )
        .order_by(Match.scheduled_at.desc())
        .limit(window)
    )
    rows = (await db.execute(stmt)).scalars().all()

    codes_newest_first: list[str] = []
    wins = draws = losses = gf = ga = 0

    for m in rows:
        if m.result is None:
            continue
        if m.home_team_id == team_id:
            gf += m.result.home_score
            ga += m.result.away_score
            if m.result.winner == "home":
                codes_newest_first.append("W")
                wins += 1
            elif m.result.winner == "draw":
                codes_newest_first.append("D")
                draws += 1
            else:
                codes_newest_first.append("L")
                losses += 1
        else:
            gf += m.result.away_score
            ga += m.result.home_score
            if m.result.winner == "away":
                codes_newest_first.append("W")
                wins += 1
            elif m.result.winner == "draw":
                codes_newest_first.append("D")
                draws += 1
            else:
                codes_newest_first.append("L")
                losses += 1

    return TeamFormSummary(
        last_5=codes_newest_first[:5],
        last_10=codes_newest_first[:10],
        wins=wins,
        draws=draws,
        losses=losses,
        goals_scored=gf,
        goals_conceded=ga,
    )


async def _head_to_head_summary(
    home_team_id: uuid.UUID,
    away_team_id: uuid.UUID,
    exclude_match_id: uuid.UUID,
    db: AsyncSession,
    home_name: str,
    away_name: str,
) -> HeadToHeadSummary:
    """Aggregate past meetings between the two teams, excluding the current fixture."""
    stmt = (
        select(Match)
        .where(
            or_(
                and_(
                    Match.home_team_id == home_team_id,
                    Match.away_team_id == away_team_id,
                ),
                and_(
                    Match.home_team_id == away_team_id,
                    Match.away_team_id == home_team_id,
                ),
            ),
            Match.status == MatchStatus.FINISHED,
            Match.id != exclude_match_id,
        )
        .order_by(Match.scheduled_at.desc())
        .limit(10)
    )
    rows = (await db.execute(stmt)).scalars().all()

    total = 0
    home_wins = draws = away_wins = 0

    for m in rows:
        if m.result is None:
            continue
        total += 1
        if m.result.winner == "draw":
            draws += 1
            continue
        # Winning team perspective: the "home" of the current fixture.
        this_match_home_won = (
            m.home_team_id == home_team_id and m.result.winner == "home"
        ) or (m.away_team_id == home_team_id and m.result.winner == "away")
        if this_match_home_won:
            home_wins += 1
        else:
            away_wins += 1

    summary: Optional[str] = None
    if total > 0:
        summary = (
            f"Last {total} meetings: "
            f"{home_name} {home_wins}W – {draws}D – {away_wins}W {away_name}."
        )

    return HeadToHeadSummary(
        total=total,
        home_wins=home_wins,
        draws=draws,
        away_wins=away_wins,
        summary=summary,
    )


@router.get(
    "/{fixture_id}",
    response_model=FixtureItem,
    summary="Single fixture with predictions and odds",
    description=(
        "Return the same FixtureItem shape the list endpoints use, for a "
        "single match by ID. Powers the /matches/[id] detail page."
    ),
)
async def get_fixture_detail(
    fixture_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    user_tier: PickTier = Depends(get_current_tier),
) -> FixtureItem:
    match = (
        await db.execute(select(Match).where(Match.id == fixture_id))
    ).scalar_one_or_none()
    if match is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Fixture {fixture_id} not found.",
        )

    pred_map = await _load_latest_predictions([match.id], db, user_tier)
    odds_map = await _load_latest_odds([match.id], db)
    item = _build_fixture_item(
        match,
        pred_map.get(match.id),
        odds_map.get(match.id),
        user_tier=user_tier,
    )
    await _enrich_with_live_scores([item], [match])
    return item


@router.get(
    "/{fixture_id}/analysis",
    response_model=FixtureAnalysisResponse,
    summary="Fixture analysis (team form + head-to-head)",
)
async def get_fixture_analysis(
    fixture_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    user_tier: PickTier = Depends(get_current_tier),
) -> FixtureAnalysisResponse:
    match = (
        await db.execute(select(Match).where(Match.id == fixture_id))
    ).scalar_one_or_none()
    if match is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Fixture {fixture_id} not found.",
        )

    pred_map = await _load_latest_predictions([match.id], db, user_tier)
    odds_map = await _load_latest_odds([match.id], db)
    fixture_item = _build_fixture_item(
        match, pred_map.get(match.id), odds_map.get(match.id), user_tier=user_tier
    )
    await _enrich_with_live_scores([fixture_item], [match])

    home_form = await _team_form_summary(match.home_team_id, db)
    away_form = await _team_form_summary(match.away_team_id, db)

    home_name = match.home_team.name if match.home_team else "Home"
    away_name = match.away_team.name if match.away_team else "Away"
    h2h = await _head_to_head_summary(
        match.home_team_id,
        match.away_team_id,
        match.id,
        db,
        home_name,
        away_name,
    )

    return FixtureAnalysisResponse(
        match=fixture_item,
        home_team_form=home_form,
        away_team_form=away_form,
        head_to_head=h2h,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Live lineups + events (via API-Football pass-through)
#
# API-Football already has /fixtures/lineups and /fixtures/events. Our Match
# rows carry the provider's fixture ID in external_id (format:
# "apifb_match_{id}"). We extract that and proxy the call, shaping the
# response to what the NOCTURNE detail page wants to render.
#
# Simple in-process TTL cache so rapid re-renders don't burn the API quota.
# ─────────────────────────────────────────────────────────────────────────────


import time as _time
import httpx as _httpx

from app.core.config import get_settings as _get_settings
from app.ingestion.adapters.api_football import (
    APIFootballAdapter as _ApiFb,
    LEAGUE_SLUG_TO_ID as _LEAGUE_SLUG_TO_ID,
    _current_season as _apifb_current_season,
)


class LineupPlayer(BaseModel):
    id: Optional[int] = None
    name: str
    number: Optional[int] = None
    position: Optional[str] = None  # "G" / "D" / "M" / "F" (API-Football codes)
    grid: Optional[str] = None  # "1:1" / "2:3" — row:col on the pitch grid


class LineupCoach(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    photo: Optional[str] = None


class TeamLineup(BaseModel):
    team_id: Optional[int] = None
    team_name: Optional[str] = None
    team_logo: Optional[str] = None
    formation: Optional[str] = None
    coach: Optional[LineupCoach] = None
    starting_xi: List[LineupPlayer] = []
    substitutes: List[LineupPlayer] = []


class FixtureLineupsResponse(BaseModel):
    fixture_id: str
    home: Optional[TeamLineup] = None
    away: Optional[TeamLineup] = None
    available: bool = False
    note: Optional[str] = None


class FixtureEvent(BaseModel):
    minute: Optional[int] = None
    extra_minute: Optional[int] = None
    team_id: Optional[int] = None
    team_name: Optional[str] = None
    team_side: Optional[str] = None  # "home" | "away"
    player_name: Optional[str] = None
    assist_name: Optional[str] = None
    type: Optional[str] = None  # "Goal" | "Card" | "subst" | "Var"
    detail: Optional[str] = None  # "Normal Goal" | "Yellow Card" | "Red Card" | …
    comments: Optional[str] = None


class FixtureEventsResponse(BaseModel):
    fixture_id: str
    events: List[FixtureEvent] = []
    available: bool = False
    note: Optional[str] = None


class FixtureTeamStats(BaseModel):
    """Per-team match stats from API-Football /fixtures/statistics.

    Keys mirror the adapter's TYPE_MAP_INT + Ball Possession. Any field
    may be None if the provider didn't return it for this match.
    """

    shots_on_target: Optional[int] = None
    shots_total: Optional[int] = None
    corners: Optional[int] = None
    yellow_cards: Optional[int] = None
    red_cards: Optional[int] = None
    fouls: Optional[int] = None
    offsides: Optional[int] = None
    passes_accurate: Optional[int] = None
    possession_pct: Optional[float] = None


class FixtureStatisticsResponse(BaseModel):
    fixture_id: str
    home: Optional[FixtureTeamStats] = None
    away: Optional[FixtureTeamStats] = None
    available: bool = False
    note: Optional[str] = None


class FixtureInjury(BaseModel):
    player_name: Optional[str] = None
    player_photo: Optional[str] = None
    team_id: Optional[int] = None
    team_name: Optional[str] = None
    team_side: Optional[str] = None  # "home" | "away"
    type: Optional[str] = None  # "Missing Fixture" | "Questionable" | …
    reason: Optional[str] = None  # specific injury ("Knee Injury", "Suspended")


class FixtureInjuriesResponse(BaseModel):
    fixture_id: str
    items: List[FixtureInjury] = []
    available: bool = False
    note: Optional[str] = None


class StandingRow(BaseModel):
    position: Optional[int] = None
    team_id: Optional[int] = None
    team_name: Optional[str] = None
    team_logo: Optional[str] = None
    played: int = 0
    wins: int = 0
    draws: int = 0
    losses: int = 0
    goals_for: int = 0
    goals_against: int = 0
    goal_difference: int = 0
    points: int = 0
    form: Optional[str] = None
    description: Optional[str] = None
    is_home_team: bool = False
    is_away_team: bool = False


class FixtureStandingsResponse(BaseModel):
    fixture_id: str
    league_name: Optional[str] = None
    season: Optional[int] = None
    rows: List[StandingRow] = []
    available: bool = False
    note: Optional[str] = None


# ── Tiny TTL cache ───────────────────────────────────────────────────────────
# Keeps responses warm for a short window so repeated page-loads and React
# Query refetches don't hammer API-Football when a match is live.

_LINEUP_TTL = 120.0  # seconds
_EVENT_TTL_LIVE = 45.0  # live match → refresh often
_EVENT_TTL_FINAL = 86400.0  # finished match → cache a day
_STATS_TTL_LIVE = 60.0  # possession/shots move fast while live
_STATS_TTL_FINAL = 86400.0
_INJURIES_TTL = 3600.0  # injuries don't change during a match
_STANDINGS_TTL = 900.0  # refresh league table every 15 min
_pass_cache: dict[str, tuple[float, Any]] = {}


def _cache_get(key: str) -> Optional[Any]:
    entry = _pass_cache.get(key)
    if entry is None:
        return None
    expiry, value = entry
    if expiry < _time.time():
        _pass_cache.pop(key, None)
        return None
    return value


def _cache_set(key: str, value: Any, ttl: float) -> None:
    _pass_cache[key] = (_time.time() + ttl, value)


def _apifb_id_for(match: Match) -> Optional[int]:
    """Extract the API-Football fixture ID from our external_id (apifb_match_123)."""
    if not match.external_id:
        return None
    parts = match.external_id.split("_")
    if len(parts) < 3 or parts[0] != "apifb" or parts[1] != "match":
        return None
    try:
        return int(parts[2])
    except ValueError:
        return None


async def _call_api_football(endpoint: str, params: dict) -> list:
    """Thin pass-through to API-Football's /{endpoint}. Returns the `response` list."""
    settings = _get_settings()
    if not settings.api_football_key:
        raise HTTPException(
            status_code=503, detail="API_FOOTBALL_KEY not configured"
        )
    async with _httpx.AsyncClient(timeout=20) as client:
        adapter = _ApiFb(
            config={
                "api_key": settings.api_football_key,
                "rate_limit_seconds": 0.2,
            },
            http_client=client,
        )
        data = await adapter._get(endpoint, params)
    if isinstance(data, list):
        return data
    if isinstance(data, dict):
        return data.get("response", []) or []
    return []


@router.get(
    "/{fixture_id}/lineup",
    response_model=FixtureLineupsResponse,
    summary="Lineups, formation and bench for both teams (via API-Football)",
)
async def get_fixture_lineup(
    fixture_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
) -> FixtureLineupsResponse:
    match = (
        await db.execute(select(Match).where(Match.id == fixture_id))
    ).scalar_one_or_none()
    if match is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Fixture {fixture_id} not found.",
        )

    apifb_id = _apifb_id_for(match)
    if apifb_id is None:
        return FixtureLineupsResponse(
            fixture_id=str(fixture_id),
            available=False,
            note="This fixture was not ingested from API-Football, so lineups are unavailable.",
        )

    cache_key = f"lineup:{apifb_id}"
    cached = _cache_get(cache_key)
    if cached is not None:
        return cached

    try:
        items = await _call_api_football("fixtures/lineups", {"fixture": apifb_id})
    except HTTPException:
        raise
    except Exception as exc:  # noqa: BLE001 — best-effort pass-through
        return FixtureLineupsResponse(
            fixture_id=str(fixture_id),
            available=False,
            note=f"Lineup provider error: {exc}",
        )

    if not items:
        out = FixtureLineupsResponse(
            fixture_id=str(fixture_id),
            available=False,
            note="Lineups not published yet — usually available ~1h before kick-off.",
        )
        _cache_set(cache_key, out, 90.0)
        return out

    # API-Football returns items ordered as [home, away] but we match on
    # team_id against the Match home_team.external_id if possible.
    home_team_apifb_id: Optional[int] = None
    away_team_apifb_id: Optional[int] = None
    # Try to extract team ID from API-Football via external_id if stored.
    # Otherwise fall back to [0]=home, [1]=away per their convention.

    def _shape_player(raw: dict) -> LineupPlayer:
        p = raw.get("player", raw)
        return LineupPlayer(
            id=p.get("id"),
            name=p.get("name") or "",
            number=p.get("number"),
            position=p.get("pos"),
            grid=p.get("grid"),
        )

    def _shape_side(raw: dict) -> TeamLineup:
        team = raw.get("team", {})
        coach_raw = raw.get("coach") or {}
        return TeamLineup(
            team_id=team.get("id"),
            team_name=team.get("name"),
            team_logo=team.get("logo"),
            formation=raw.get("formation"),
            coach=(
                LineupCoach(
                    id=coach_raw.get("id"),
                    name=coach_raw.get("name"),
                    photo=coach_raw.get("photo"),
                )
                if coach_raw
                else None
            ),
            starting_xi=[_shape_player(p) for p in (raw.get("startXI") or [])],
            substitutes=[_shape_player(p) for p in (raw.get("substitutes") or [])],
        )

    home_side: Optional[TeamLineup] = None
    away_side: Optional[TeamLineup] = None

    if len(items) >= 1:
        home_side = _shape_side(items[0])
    if len(items) >= 2:
        away_side = _shape_side(items[1])

    # If the Match's home team is actually the 2nd item, swap. We compare on
    # team name since that's what we reliably have stored locally.
    if home_side and away_side and match.home_team and match.away_team:
        local_home = (match.home_team.name or "").strip().lower()
        if (
            home_side.team_name
            and home_side.team_name.strip().lower() != local_home
            and away_side.team_name
            and away_side.team_name.strip().lower() == local_home
        ):
            home_side, away_side = away_side, home_side

    out = FixtureLineupsResponse(
        fixture_id=str(fixture_id),
        home=home_side,
        away=away_side,
        available=bool(home_side or away_side),
    )
    _cache_set(cache_key, out, _LINEUP_TTL)
    return out


@router.get(
    "/{fixture_id}/events",
    response_model=FixtureEventsResponse,
    summary="Match events timeline — goals, cards, subs, VAR (via API-Football)",
)
async def get_fixture_events(
    fixture_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
) -> FixtureEventsResponse:
    match = (
        await db.execute(select(Match).where(Match.id == fixture_id))
    ).scalar_one_or_none()
    if match is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Fixture {fixture_id} not found.",
        )

    apifb_id = _apifb_id_for(match)
    if apifb_id is None:
        return FixtureEventsResponse(
            fixture_id=str(fixture_id),
            available=False,
            note="This fixture was not ingested from API-Football, so events are unavailable.",
        )

    cache_key = f"events:{apifb_id}"
    cached = _cache_get(cache_key)
    if cached is not None:
        return cached

    try:
        items = await _call_api_football("fixtures/events", {"fixture": apifb_id})
    except HTTPException:
        raise
    except Exception as exc:  # noqa: BLE001
        return FixtureEventsResponse(
            fixture_id=str(fixture_id),
            available=False,
            note=f"Events provider error: {exc}",
        )

    # Build local team name → side map so the UI can colour-code events.
    home_name = (match.home_team.name or "").strip().lower() if match.home_team else ""
    away_name = (match.away_team.name or "").strip().lower() if match.away_team else ""

    events: list[FixtureEvent] = []
    for raw in items:
        tm = raw.get("time") or {}
        team = raw.get("team") or {}
        player = raw.get("player") or {}
        assist = raw.get("assist") or {}
        team_name = team.get("name")
        team_side: Optional[str] = None
        if team_name:
            low = team_name.strip().lower()
            if low == home_name:
                team_side = "home"
            elif low == away_name:
                team_side = "away"
        events.append(
            FixtureEvent(
                minute=tm.get("elapsed"),
                extra_minute=tm.get("extra"),
                team_id=team.get("id"),
                team_name=team_name,
                team_side=team_side,
                player_name=player.get("name"),
                assist_name=assist.get("name"),
                type=raw.get("type"),
                detail=raw.get("detail"),
                comments=raw.get("comments"),
            )
        )

    # Chronological order
    events.sort(
        key=lambda e: ((e.minute or 0), (e.extra_minute or 0))
    )

    out = FixtureEventsResponse(
        fixture_id=str(fixture_id),
        events=events,
        available=True,
    )
    ttl = _EVENT_TTL_LIVE if match.status == MatchStatus.LIVE else _EVENT_TTL_FINAL
    _cache_set(cache_key, out, ttl)
    return out


# ─────────────────────────────────────────────────────────────────────────────
# Live match statistics — possession, shots, corners, cards (via API-Football)
# ─────────────────────────────────────────────────────────────────────────────


_STAT_TYPE_MAP_INT = {
    "Shots on Goal": "shots_on_target",
    "Total Shots": "shots_total",
    "Corner Kicks": "corners",
    "Yellow Cards": "yellow_cards",
    "Red Cards": "red_cards",
    "Fouls": "fouls",
    "Offsides": "offsides",
    "Passes accurate": "passes_accurate",
}


def _stat_as_int(v: Any) -> Optional[int]:
    if v is None:
        return None
    if isinstance(v, str):
        v = v.strip().rstrip("%")
        if not v:
            return None
    try:
        return int(float(v))
    except (TypeError, ValueError):
        return None


def _stat_as_float(v: Any) -> Optional[float]:
    if v is None:
        return None
    if isinstance(v, str):
        v = v.strip().rstrip("%")
        if not v:
            return None
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


@router.get(
    "/{fixture_id}/statistics",
    response_model=FixtureStatisticsResponse,
    summary="Live match statistics — shots, possession, corners (via API-Football)",
)
async def get_fixture_statistics(
    fixture_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
) -> FixtureStatisticsResponse:
    match = (
        await db.execute(select(Match).where(Match.id == fixture_id))
    ).scalar_one_or_none()
    if match is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Fixture {fixture_id} not found.",
        )

    apifb_id = _apifb_id_for(match)
    if apifb_id is None:
        return FixtureStatisticsResponse(
            fixture_id=str(fixture_id),
            available=False,
            note="This fixture was not ingested from API-Football, so stats are unavailable.",
        )

    cache_key = f"stats:{apifb_id}"
    cached = _cache_get(cache_key)
    if cached is not None:
        return cached

    try:
        items = await _call_api_football(
            "fixtures/statistics", {"fixture": apifb_id}
        )
    except HTTPException:
        raise
    except Exception as exc:  # noqa: BLE001
        return FixtureStatisticsResponse(
            fixture_id=str(fixture_id),
            available=False,
            note=f"Stats provider error: {exc}",
        )

    if not items:
        out = FixtureStatisticsResponse(
            fixture_id=str(fixture_id),
            available=False,
            note="Match statistics not published yet — usually appear shortly after kick-off.",
        )
        _cache_set(cache_key, out, 60.0)
        return out

    # Local home name for side mapping; API-Football returns items as [home, away]
    # but we double-check by team name to survive any ordering quirks.
    local_home = (match.home_team.name or "").strip().lower() if match.home_team else ""

    sides: dict[str, FixtureTeamStats] = {}
    order: list[Optional[str]] = []
    for i, entry in enumerate(items[:2]):
        team = entry.get("team", {}) or {}
        name = (team.get("name") or "").strip().lower()
        if name == local_home:
            side = "home"
        elif name and len(sides) == 0 and i == 0 and local_home and name != local_home:
            side = "away"
        else:
            side = "home" if i == 0 else "away"
        order.append(side)
        stats = FixtureTeamStats()
        for stat in entry.get("statistics", []) or []:
            label = stat.get("type", "")
            value = stat.get("value")
            if label == "Ball Possession":
                stats.possession_pct = _stat_as_float(value)
            elif label in _STAT_TYPE_MAP_INT:
                setattr(stats, _STAT_TYPE_MAP_INT[label], _stat_as_int(value))
        sides[side] = stats

    # Fix accidental collisions (both sides mapped to the same key) by
    # reverting to positional order.
    if len(sides) < 2:
        sides = {}
        for i, entry in enumerate(items[:2]):
            side = "home" if i == 0 else "away"
            stats = FixtureTeamStats()
            for stat in entry.get("statistics", []) or []:
                label = stat.get("type", "")
                value = stat.get("value")
                if label == "Ball Possession":
                    stats.possession_pct = _stat_as_float(value)
                elif label in _STAT_TYPE_MAP_INT:
                    setattr(stats, _STAT_TYPE_MAP_INT[label], _stat_as_int(value))
            sides[side] = stats

    out = FixtureStatisticsResponse(
        fixture_id=str(fixture_id),
        home=sides.get("home"),
        away=sides.get("away"),
        available=True,
    )
    ttl = _STATS_TTL_LIVE if match.status == MatchStatus.LIVE else _STATS_TTL_FINAL
    _cache_set(cache_key, out, ttl)
    return out


# ─────────────────────────────────────────────────────────────────────────────
# Injury list for a fixture (via API-Football /injuries?fixture=)
# ─────────────────────────────────────────────────────────────────────────────


@router.get(
    "/{fixture_id}/injuries",
    response_model=FixtureInjuriesResponse,
    summary="Injury list for both teams (via API-Football)",
)
async def get_fixture_injuries(
    fixture_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
) -> FixtureInjuriesResponse:
    match = (
        await db.execute(select(Match).where(Match.id == fixture_id))
    ).scalar_one_or_none()
    if match is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Fixture {fixture_id} not found.",
        )

    apifb_id = _apifb_id_for(match)
    if apifb_id is None:
        return FixtureInjuriesResponse(
            fixture_id=str(fixture_id),
            available=False,
            note="This fixture was not ingested from API-Football, so injuries are unavailable.",
        )

    cache_key = f"injuries:{apifb_id}"
    cached = _cache_get(cache_key)
    if cached is not None:
        return cached

    try:
        items = await _call_api_football("injuries", {"fixture": apifb_id})
    except HTTPException:
        raise
    except Exception as exc:  # noqa: BLE001
        return FixtureInjuriesResponse(
            fixture_id=str(fixture_id),
            available=False,
            note=f"Injury provider error: {exc}",
        )

    local_home = (match.home_team.name or "").strip().lower() if match.home_team else ""
    local_away = (match.away_team.name or "").strip().lower() if match.away_team else ""

    injuries: list[FixtureInjury] = []
    for raw in items:
        player = raw.get("player") or {}
        team = raw.get("team") or {}
        team_name = team.get("name")
        side: Optional[str] = None
        if team_name:
            low = team_name.strip().lower()
            if low == local_home:
                side = "home"
            elif low == local_away:
                side = "away"
        injuries.append(
            FixtureInjury(
                player_name=player.get("name"),
                player_photo=player.get("photo"),
                team_id=team.get("id"),
                team_name=team_name,
                team_side=side,
                type=player.get("type"),
                reason=player.get("reason"),
            )
        )

    out = FixtureInjuriesResponse(
        fixture_id=str(fixture_id),
        items=injuries,
        available=True,
        note=(
            "API-Football does not list any injuries for this fixture."
            if not injuries
            else None
        ),
    )
    _cache_set(cache_key, out, _INJURIES_TTL)
    return out


# ─────────────────────────────────────────────────────────────────────────────
# League standings for the fixture's league (via API-Football /standings)
# ─────────────────────────────────────────────────────────────────────────────


@router.get(
    "/{fixture_id}/standings",
    response_model=FixtureStandingsResponse,
    summary="League table for the fixture's league (via API-Football)",
)
async def get_fixture_standings(
    fixture_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
) -> FixtureStandingsResponse:
    match = (
        await db.execute(select(Match).where(Match.id == fixture_id))
    ).scalar_one_or_none()
    if match is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Fixture {fixture_id} not found.",
        )

    # Resolve API-Football league id from the Match's league slug.
    league = match.league
    league_slug = (league.slug or "").strip() if league else ""
    apifb_league_id = _LEAGUE_SLUG_TO_ID.get(league_slug)
    if apifb_league_id is None:
        return FixtureStandingsResponse(
            fixture_id=str(fixture_id),
            available=False,
            note=(
                "League table is unavailable — this league is not mapped to "
                "API-Football standings."
            ),
        )

    season = _apifb_current_season()
    cache_key = f"standings:{apifb_league_id}:{season}"
    cached = _cache_get(cache_key)
    if cached is not None:
        # Re-decorate the cached rows with is_home/is_away for this specific
        # fixture (teams differ per fixture, league standings don't).
        rows = _mark_fixture_teams_in_standings(cached.rows, match)
        return FixtureStandingsResponse(
            fixture_id=str(fixture_id),
            league_name=cached.league_name,
            season=cached.season,
            rows=rows,
            available=cached.available,
            note=cached.note,
        )

    try:
        data = await _call_api_football(
            "standings", {"league": apifb_league_id, "season": season}
        )
    except HTTPException:
        raise
    except Exception as exc:  # noqa: BLE001
        return FixtureStandingsResponse(
            fixture_id=str(fixture_id),
            available=False,
            note=f"Standings provider error: {exc}",
        )

    if not data:
        out = FixtureStandingsResponse(
            fixture_id=str(fixture_id),
            season=season,
            available=False,
            note="API-Football did not return a standings table for this league/season.",
        )
        _cache_set(cache_key, out, 120.0)
        return out

    league_block = data[0].get("league", {}) or {}
    league_name = league_block.get("name")
    rows: list[StandingRow] = []
    for group in league_block.get("standings", []) or []:
        for entry in group:
            team = entry.get("team", {}) or {}
            all_stats = entry.get("all", {}) or {}
            goals = all_stats.get("goals", {}) or {}
            rows.append(
                StandingRow(
                    position=entry.get("rank"),
                    team_id=team.get("id"),
                    team_name=team.get("name"),
                    team_logo=team.get("logo"),
                    played=all_stats.get("played", 0) or 0,
                    wins=all_stats.get("win", 0) or 0,
                    draws=all_stats.get("draw", 0) or 0,
                    losses=all_stats.get("lose", 0) or 0,
                    goals_for=goals.get("for", 0) or 0,
                    goals_against=goals.get("against", 0) or 0,
                    goal_difference=entry.get("goalsDiff", 0) or 0,
                    points=entry.get("points", 0) or 0,
                    form=entry.get("form"),
                    description=entry.get("description"),
                )
            )

    marked = _mark_fixture_teams_in_standings(rows, match)
    out = FixtureStandingsResponse(
        fixture_id=str(fixture_id),
        league_name=league_name,
        season=season,
        rows=marked,
        available=bool(rows),
        note=None if rows else "No standings returned by provider.",
    )
    _cache_set(cache_key, out, _STANDINGS_TTL)
    return out


def _mark_fixture_teams_in_standings(
    rows: List[StandingRow], match: Match
) -> List[StandingRow]:
    """Stamp is_home_team / is_away_team flags on standings rows by team name."""
    home_name = (match.home_team.name or "").strip().lower() if match.home_team else ""
    away_name = (match.away_team.name or "").strip().lower() if match.away_team else ""
    out: list[StandingRow] = []
    for r in rows:
        name = (r.team_name or "").strip().lower()
        out.append(
            r.model_copy(
                update={
                    "is_home_team": bool(name) and name == home_name,
                    "is_away_team": bool(name) and name == away_name,
                }
            )
        )
    return out
