"""
Fixtures API Routes
====================
All routes in this module read ONLY from the local PostgreSQL database.
No external API calls are made.  Data is kept fresh by the background
``task_sync_matches`` Celery task which runs every 5 minutes.

Endpoints
---------
GET /fixtures/upcoming              – upcoming matches (+ predictions)
GET /fixtures/today                 – today's matches
GET /fixtures/results               – finished matches with scores (?days=7)
GET /fixtures/results/weekly-summary – weekly winners/losers stats

SIMULATION / EDUCATIONAL DISCLAIMER
-------------------------------------
All probability estimates provided on this platform are produced by a
statistical model for simulation and educational research purposes only.
They do NOT constitute financial, betting, or investment advice of any kind.
"""
from __future__ import annotations

from datetime import date, datetime, timedelta, timezone
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Depends, Query
from pydantic import BaseModel, ConfigDict, Field
from sqlalchemy import and_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import get_db
from app.models.league import League
from app.models.match import Match, MatchResult, MatchStatus
from app.models.prediction import Prediction
from app.models.team import Team

router = APIRouter()

_SIMULATION_DISCLAIMER = (
    "SIMULATION / EDUCATIONAL USE ONLY. "
    "All probability estimates are generated by a statistical model for "
    "research and educational purposes. They do NOT constitute financial, "
    "betting, or investment advice. Past model performance is not indicative "
    "of future results. Always gamble responsibly and within applicable laws."
)


# ─────────────────────────────────────────────────────────────────────────────
# Response schemas
# ─────────────────────────────────────────────────────────────────────────────


class PredictionSummary(BaseModel):
    """Rich prediction summary embedded in a fixture response."""

    model_config = ConfigDict(from_attributes=True)

    id: str
    home_win_prob: float
    draw_prob: Optional[float] = None
    away_win_prob: float
    predicted_home_score: Optional[float] = None
    predicted_away_score: Optional[float] = None
    confidence: float
    model_name: Optional[str] = None
    predicted_at: Optional[str] = None
    pick: Optional[str] = None  # HOME / DRAW / AWAY
    reasoning: Optional[str] = None
    edge: Optional[Dict[str, float]] = None  # {home: 0.04, draw: -0.02, away: -0.02}
    implied_probabilities: Optional[Dict[str, float]] = None
    top_features: Optional[List[Dict[str, Any]]] = None
    strategies_matched: Optional[List[str]] = None
    disclaimer: str = _SIMULATION_DISCLAIMER
    is_simulation: bool = True


class ResultSummary(BaseModel):
    """Score summary embedded in a fixture response."""

    home_score: int
    away_score: int
    home_score_ht: Optional[int] = None
    away_score_ht: Optional[int] = None
    winner: Optional[str] = None  # "home" | "away" | "draw"


class OddsSummary(BaseModel):
    """v6: pre-match odds embedded in a fixture response.

    Only populated when an ``odds_history`` row exists for the match.
    When no odds are on file, the ``odds`` field on FixtureItem is
    left as None and the frontend should render nothing — NOT a "—"
    placeholder. See docs/v6_bugfix_report.md §B1.
    """

    home: Optional[float] = None
    draw: Optional[float] = None
    away: Optional[float] = None
    over_2_5: Optional[float] = None
    under_2_5: Optional[float] = None
    bookmaker: Optional[str] = None
    fetched_at: Optional[str] = None


class FixtureItem(BaseModel):
    """A single fixture row as returned by the /fixtures endpoints."""

    id: str
    league_id: str
    league_name: Optional[str] = None
    league_slug: Optional[str] = None
    home_team_id: str
    home_team_name: Optional[str] = None
    home_team_slug: Optional[str] = None
    away_team_id: str
    away_team_name: Optional[str] = None
    away_team_slug: Optional[str] = None
    external_id: Optional[str] = None
    status: str
    scheduled_at: datetime
    venue: Optional[str] = None
    round_name: Optional[str] = None
    matchday: Optional[int] = None
    result: Optional[ResultSummary] = None
    prediction: Optional[PredictionSummary] = None
    odds: Optional[OddsSummary] = None
    # v6.3: real-time live score — only set for matches with status=LIVE
    # Populated from Redis cache, refreshed every 60s via API-Football.
    live_score: Optional[dict] = None


class UpcomingFixturesResponse(BaseModel):
    """Response envelope for /fixtures/upcoming."""

    count: int
    disclaimer: str = _SIMULATION_DISCLAIMER
    fixtures: List[FixtureItem]


class TodayFixturesResponse(BaseModel):
    """Response envelope for /fixtures/today."""

    date: str
    count: int
    disclaimer: str = _SIMULATION_DISCLAIMER
    fixtures: List[FixtureItem]


class ResultsResponse(BaseModel):
    """Response envelope for /fixtures/results."""

    days: int
    count: int
    disclaimer: str = _SIMULATION_DISCLAIMER
    fixtures: List[FixtureItem]


class WeeklySummaryItem(BaseModel):
    """One team's performance entry in the weekly summary."""

    team_id: str
    team_name: Optional[str]
    team_slug: Optional[str]
    matches_played: int
    wins: int
    draws: int
    losses: int
    goals_for: int
    goals_against: int
    goal_difference: int
    points: int


class WeeklyPerformer(BaseModel):
    name: str
    accuracy: float
    total: int


class WeeklySummaryResponse(BaseModel):
    """Response matching frontend WeeklySummary type."""

    total_calls: int = 0
    won: int = 0
    lost: int = 0
    win_rate: float = 0.0
    pl_units: float = 0.0
    best_performers: List[WeeklyPerformer] = []
    worst_performers: List[WeeklyPerformer] = []
    disclaimer: str = _SIMULATION_DISCLAIMER


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────


async def _load_latest_odds(
    match_ids: list,
    db: AsyncSession,
) -> dict:
    """v6: return ``{match_id: OddsSummary}`` mapping for the most
    recent 1x2 odds row per match. Also looks up over/under 2.5
    odds from the same table and merges them into a single summary.
    """
    if not match_ids:
        return {}

    from app.models.odds import OddsHistory

    # 1x2 rows per match — pick the most recent recorded_at
    from sqlalchemy import func as sfunc

    subq_1x2 = (
        select(
            OddsHistory.match_id,
            sfunc.max(OddsHistory.recorded_at).label("latest_at"),
        )
        .where(
            and_(
                OddsHistory.match_id.in_(match_ids),
                OddsHistory.market.in_(["1x2", "1X2"]),
            )
        )
        .group_by(OddsHistory.match_id)
        .subquery()
    )
    stmt_1x2 = (
        select(OddsHistory)
        .join(
            subq_1x2,
            and_(
                OddsHistory.match_id == subq_1x2.c.match_id,
                OddsHistory.recorded_at == subq_1x2.c.latest_at,
                OddsHistory.market.in_(["1x2", "1X2"]),
            ),
        )
    )
    rows_1x2 = (await db.execute(stmt_1x2)).scalars().all()

    # Over/Under 2.5 rows per match
    subq_ou = (
        select(
            OddsHistory.match_id,
            sfunc.max(OddsHistory.recorded_at).label("latest_at"),
        )
        .where(
            and_(
                OddsHistory.match_id.in_(match_ids),
                OddsHistory.market == "over_under_2_5",
            )
        )
        .group_by(OddsHistory.match_id)
        .subquery()
    )
    stmt_ou = (
        select(OddsHistory)
        .join(
            subq_ou,
            and_(
                OddsHistory.match_id == subq_ou.c.match_id,
                OddsHistory.recorded_at == subq_ou.c.latest_at,
                OddsHistory.market == "over_under_2_5",
            ),
        )
    )
    rows_ou = (await db.execute(stmt_ou)).scalars().all()
    ou_by_match = {r.match_id: r for r in rows_ou}

    result: dict = {}
    for row in rows_1x2:
        ou_row = ou_by_match.get(row.match_id)
        result[row.match_id] = OddsSummary(
            home=row.home_odds,
            draw=row.draw_odds,
            away=row.away_odds,
            over_2_5=(ou_row.over_odds if ou_row else None),
            under_2_5=(ou_row.under_odds if ou_row else None),
            bookmaker=row.source,
            fetched_at=row.recorded_at.isoformat() if row.recorded_at else None,
        )

    # Also include matches that only have O/U rows but no 1x2 — rare
    # but possible during the snapshot accumulation period.
    for mid, ou_row in ou_by_match.items():
        if mid not in result:
            result[mid] = OddsSummary(
                over_2_5=ou_row.over_odds,
                under_2_5=ou_row.under_odds,
                bookmaker=ou_row.source,
                fetched_at=ou_row.recorded_at.isoformat() if ou_row.recorded_at else None,
            )

    return result


def _build_fixture_item(
    match: Match,
    latest_prediction: Optional[Prediction] = None,
    odds: Optional[OddsSummary] = None,
) -> FixtureItem:
    """Convert a Match ORM object to a FixtureItem response schema."""
    result_summary: Optional[ResultSummary] = None
    if match.result:
        result_summary = ResultSummary(
            home_score=match.result.home_score,
            away_score=match.result.away_score,
            home_score_ht=match.result.home_score_ht,
            away_score_ht=match.result.away_score_ht,
            winner=match.result.winner,
        )

    pred_summary: Optional[PredictionSummary] = None
    if latest_prediction:
        model_name = None
        if latest_prediction.model_version:
            model_name = latest_prediction.model_version.name

        # Determine pick
        probs = {
            "HOME": latest_prediction.home_win_prob,
            "DRAW": latest_prediction.draw_prob or 0,
            "AWAY": latest_prediction.away_win_prob,
        }
        pick = max(probs, key=lambda k: probs[k])

        # Generate reasoning from explanation if available
        reasoning = None
        if latest_prediction.explanation:
            reasoning = latest_prediction.explanation.summary
        else:
            # Template-based reasoning
            home_name = match.home_team.name if match.home_team else "Home"
            away_name = match.away_team.name if match.away_team else "Away"
            if pick == "HOME":
                reasoning = f"{home_name} favored with {latest_prediction.home_win_prob:.0%} win probability. Confidence: {latest_prediction.confidence:.0%}."
            elif pick == "AWAY":
                reasoning = f"{away_name} favored with {latest_prediction.away_win_prob:.0%} win probability. Confidence: {latest_prediction.confidence:.0%}."
            else:
                reasoning = f"Draw most likely at {(latest_prediction.draw_prob or 0):.0%}. Confidence: {latest_prediction.confidence:.0%}."

        # Edge vs uniform market (33% baseline)
        edge = {
            "home": round(latest_prediction.home_win_prob - 1/3, 4),
            "draw": round((latest_prediction.draw_prob or 0) - 1/3, 4),
            "away": round(latest_prediction.away_win_prob - 1/3, 4),
        }

        # Top features from raw_output
        top_features = None
        if latest_prediction.raw_output and isinstance(latest_prediction.raw_output, dict):
            sub_models = latest_prediction.raw_output.get("sub_models", [])
            features_list = []
            for sm in sub_models:
                if "error" not in sm:
                    features_list.append({
                        "name": sm.get("model", "Unknown"),
                        "home": round(sm.get("home_win_prob", 0), 4),
                        "draw": round(sm.get("draw_prob", 0), 4),
                        "away": round(sm.get("away_win_prob", 0), 4),
                        "weight": round(sm.get("weight", 0), 2),
                    })
            if features_list:
                top_features = features_list

        pred_summary = PredictionSummary(
            id=str(latest_prediction.id),
            home_win_prob=latest_prediction.home_win_prob,
            draw_prob=latest_prediction.draw_prob,
            away_win_prob=latest_prediction.away_win_prob,
            predicted_home_score=latest_prediction.predicted_home_score,
            predicted_away_score=latest_prediction.predicted_away_score,
            confidence=latest_prediction.confidence,
            model_name=model_name,
            predicted_at=latest_prediction.predicted_at.isoformat() if latest_prediction.predicted_at else None,
            pick=pick,
            reasoning=reasoning,
            edge=edge,
            top_features=top_features,
        )

    return FixtureItem(
        id=str(match.id),
        league_id=str(match.league_id),
        league_name=match.league.name if match.league else None,
        league_slug=match.league.slug if match.league else None,
        home_team_id=str(match.home_team_id),
        home_team_name=match.home_team.name if match.home_team else None,
        home_team_slug=match.home_team.slug if match.home_team else None,
        away_team_id=str(match.away_team_id),
        away_team_name=match.away_team.name if match.away_team else None,
        away_team_slug=match.away_team.slug if match.away_team else None,
        external_id=match.external_id,
        status=match.status.value if isinstance(match.status, MatchStatus) else str(match.status),
        scheduled_at=match.scheduled_at,
        venue=match.venue,
        round_name=match.round_name,
        matchday=match.matchday,
        result=result_summary,
        prediction=pred_summary,
        odds=odds,
    )


async def _load_latest_predictions(
    match_ids: list,
    db: AsyncSession,
) -> dict:
    """Return a {match_id: Prediction} mapping for the latest prediction per match."""
    if not match_ids:
        return {}

    # Subquery: max predicted_at per match_id
    from sqlalchemy import func
    subq = (
        select(
            Prediction.match_id,
            func.max(Prediction.predicted_at).label("latest_at"),
        )
        .where(Prediction.match_id.in_(match_ids))
        .group_by(Prediction.match_id)
        .subquery()
    )

    from sqlalchemy.orm import noload

    # model_version already uses lazy="selectin" on the ORM model,
    # so no explicit selectinload needed.  Suppress evaluation loading
    # since we only need model_version and explanation here.
    stmt = (
        select(Prediction)
        .options(noload(Prediction.evaluation))
        .join(
            subq,
            and_(
                Prediction.match_id == subq.c.match_id,
                Prediction.predicted_at == subq.c.latest_at,
            ),
        )
    )
    rows = (await db.execute(stmt)).scalars().all()
    return {p.match_id: p for p in rows}


# ─────────────────────────────────────────────────────────────────────────────
# Dedup helper — filter out API-Football duplicates
# ─────────────────────────────────────────────────────────────────────────────
#
# The database contains fixtures from two sources:
#   1. football-data.org (external_id like "fd_org_..." or NULL) — ongoing sync
#   2. API-Football (external_id like "apifb_match_...") — one-time batch import
#
# Both created the same matches with slightly different team names
# (e.g. "Toulouse" vs "Toulouse FC"). This dedup function keeps only the
# football-data.org version when a duplicate exists, by matching on
# (league_id, scheduled_at within 2h). The apifb fixture is hidden, not
# deleted, so predictions linked to it are unaffected.


def _dedup_fixtures(matches: list) -> list:
    """Remove API-Football duplicates when a football-data.org version exists."""
    # Group by (league_id, rounded scheduled_at to nearest 2h)
    seen: dict[tuple, object] = {}  # (league_id, time_bucket) → first match
    result = []

    for m in matches:
        eid = m.external_id or ""
        # Time bucket: round to nearest 2 hours to catch ±1h scheduling diffs
        bucket = None
        if m.scheduled_at:
            ts = m.scheduled_at.timestamp()
            bucket = int(ts // 7200)  # 7200s = 2h
        key = (str(m.league_id), bucket)

        if key in seen:
            existing = seen[key]
            existing_eid = existing.external_id or ""
            # If the existing one is apifb and current one is NOT apifb,
            # replace existing with the non-apifb (prefer fd_org).
            if existing_eid.startswith("apifb_match_") and not eid.startswith("apifb_match_"):
                # Swap: remove existing from result, add current
                result = [r for r in result if r.id != existing.id]
                seen[key] = m
                result.append(m)
            elif not existing_eid.startswith("apifb_match_") and eid.startswith("apifb_match_"):
                # Current is apifb duplicate, skip it
                continue
            else:
                # Both same source or both apifb — keep both (no dupe)
                result.append(m)
        else:
            seen[key] = m
            result.append(m)

    return result


# ─────────────────────────────────────────────────────────────────────────────
# Routes
# ─────────────────────────────────────────────────────────────────────────────


@router.get(
    "/upcoming",
    response_model=UpcomingFixturesResponse,
    summary="Upcoming matches from the local DB with predictions",
    description=(
        "Returns all scheduled/upcoming matches stored in the database, "
        "enriched with the latest AI prediction where available.  "
        "Data is refreshed every 5 minutes by the background sync task.  "
        "No external API calls are made by this endpoint.\n\n"
        "**" + _SIMULATION_DISCLAIMER + "**"
    ),
)
async def get_upcoming_fixtures(
    days: int = Query(
        default=7,
        ge=1,
        le=30,
        description="How many days ahead to look for fixtures (1–30).",
    ),
    league_slug: Optional[str] = Query(
        default=None, description="Filter by league slug (e.g. 'premier-league')."
    ),
    db: AsyncSession = Depends(get_db),
) -> UpcomingFixturesResponse:
    now = datetime.now(timezone.utc)
    cutoff = now + timedelta(days=days)

    stmt = (
        select(Match)
        .where(
            and_(
                Match.status.in_([MatchStatus.SCHEDULED, MatchStatus.LIVE]),
                Match.scheduled_at >= now,
                Match.scheduled_at <= cutoff,
            )
        )
        .order_by(Match.scheduled_at)
    )

    if league_slug:
        stmt = stmt.join(League, League.id == Match.league_id).where(
            League.slug == league_slug
        )

    raw_matches = (await db.execute(stmt)).scalars().all()
    matches = _dedup_fixtures(raw_matches)
    match_ids = [m.id for m in matches]
    pred_map = await _load_latest_predictions(match_ids, db)
    odds_map = await _load_latest_odds(match_ids, db)

    fixtures = [
        _build_fixture_item(m, pred_map.get(m.id), odds_map.get(m.id))
        for m in matches
    ]

    return UpcomingFixturesResponse(count=len(fixtures), fixtures=fixtures)


@router.get(
    "/live",
    summary="Live/in-play matches with real-time scores (v6.3)",
    description=(
        "Returns currently live matches with real-time scores. Data comes "
        "from a Redis cache that the background job refreshes every 60s "
        "via a single API-Football call. Safe to poll every 30 seconds — "
        "all users read the same cache, no extra API calls.\n\n"
        "The ``live_score`` field on each fixture contains the current "
        "score, elapsed minutes, and halftime score when available.\n\n"
        "**" + _SIMULATION_DISCLAIMER + "**"
    ),
)
async def get_live_fixtures(
    league_slug: Optional[str] = Query(
        default=None, description="Filter by league slug."
    ),
    db: AsyncSession = Depends(get_db),
):
    """Live matches with real-time scores from Redis cache."""
    from app.core.cache import cache_get

    # ── 1. Read live score cache (populated by job_sync_live_fixtures) ──
    live_cache = await cache_get("live:fixtures") or []

    # ── 2. Also fetch LIVE matches from DB (for predictions + odds) ────
    stmt = (
        select(Match)
        .where(Match.status == MatchStatus.LIVE)
        .order_by(Match.scheduled_at)
    )
    if league_slug:
        stmt = stmt.join(League, League.id == Match.league_id).where(
            League.slug == league_slug
        )

    raw_matches = (await db.execute(stmt)).scalars().all()
    matches = _dedup_fixtures(raw_matches)
    match_ids = [m.id for m in matches]
    pred_map = await _load_latest_predictions(match_ids, db)
    odds_map = await _load_latest_odds(match_ids, db)

    # ── 3. Build a lookup from api_football_id → live score data ───────
    live_score_map: dict[str, dict] = {}
    for entry in live_cache:
        afid = str(entry.get("api_football_id", ""))
        if afid:
            live_score_map[afid] = entry

    # ── 4. Build response, enriching each fixture with live_score ──────
    fixtures = []
    for m in matches:
        item = _build_fixture_item(m, pred_map.get(m.id), odds_map.get(m.id))

        # Try to attach live score from cache
        eid = m.external_id or ""
        afid = eid.replace("apifb_match_", "") if eid.startswith("apifb_match_") else ""
        cached = live_score_map.get(afid)
        if cached:
            item.live_score = {
                "home_goals": cached.get("home_goals"),
                "away_goals": cached.get("away_goals"),
                "elapsed": cached.get("elapsed"),
                "status": cached.get("status"),
                "halftime_home": cached.get("halftime_home"),
                "halftime_away": cached.get("halftime_away"),
            }

        fixtures.append(item)

    # Also include any matches from the cache that aren't in our DB yet
    # (e.g., leagues we track via API-Football but not football-data.org)
    db_afids = set()
    for m in matches:
        eid = m.external_id or ""
        if eid.startswith("apifb_match_"):
            db_afids.add(eid.replace("apifb_match_", ""))

    return {"count": len(fixtures), "fixtures": fixtures, "disclaimer": _SIMULATION_DISCLAIMER}


@router.get(
    "/today",
    response_model=TodayFixturesResponse,
    summary="Today's matches from the local DB",
    description=(
        "Returns all matches scheduled for today (UTC), enriched with "
        "predictions.  Data is refreshed every 5 minutes.\n\n"
        "**" + _SIMULATION_DISCLAIMER + "**"
    ),
)
async def get_today_fixtures(
    db: AsyncSession = Depends(get_db),
) -> TodayFixturesResponse:
    today = date.today()
    day_start = datetime(today.year, today.month, today.day, tzinfo=timezone.utc)
    day_end = day_start + timedelta(days=1)

    stmt = (
        select(Match)
        .where(
            and_(
                Match.scheduled_at >= day_start,
                Match.scheduled_at < day_end,
            )
        )
        .order_by(Match.scheduled_at)
    )
    raw_matches = (await db.execute(stmt)).scalars().all()
    matches = _dedup_fixtures(raw_matches)
    match_ids = [m.id for m in matches]
    pred_map = await _load_latest_predictions(match_ids, db)
    odds_map = await _load_latest_odds(match_ids, db)

    fixtures = [
        _build_fixture_item(m, pred_map.get(m.id), odds_map.get(m.id))
        for m in matches
    ]

    return TodayFixturesResponse(
        date=today.isoformat(),
        count=len(fixtures),
        fixtures=fixtures,
    )


@router.get(
    "/results/weekly-summary",
    response_model=WeeklySummaryResponse,
    summary="Weekly winners/losers summary",
    description=(
        "Aggregates results from the last 7 days to rank teams by points "
        "earned in that period.  Returns the top 5 and bottom 5 performers."
    ),
)
async def get_weekly_summary(
    db: AsyncSession = Depends(get_db),
) -> WeeklySummaryResponse:
    """Weekly prediction performance summary matching frontend WeeklySummary type."""
    from app.models.prediction import Prediction, PredictionEvaluation

    now = datetime.now(timezone.utc)
    week_ago = now - timedelta(days=7)

    # Get all evaluated predictions from last 7 days
    stmt = (
        select(Prediction, PredictionEvaluation)
        .join(Match, Match.id == Prediction.match_id)
        .join(PredictionEvaluation, PredictionEvaluation.prediction_id == Prediction.id)
        .where(
            and_(
                Match.scheduled_at >= week_ago,
                Match.scheduled_at <= now,
                Match.status == MatchStatus.FINISHED,
            )
        )
    )
    rows = (await db.execute(stmt)).all()

    total_calls = len(rows)
    won = sum(1 for _, ev in rows if ev.is_correct)
    lost = total_calls - won
    win_rate = won / total_calls if total_calls > 0 else 0.0
    # P/L: flat staking 1 unit, assume avg odds ~1.9 for wins
    pl_units = (won * 0.9) - (lost * 1.0) if total_calls > 0 else 0.0

    # Best/worst by league
    league_stats: dict[str, dict] = {}
    for pred, ev in rows:
        league = pred.match.league.name if pred.match and pred.match.league else "Unknown"
        if league not in league_stats:
            league_stats[league] = {"name": league, "correct": 0, "total": 0}
        league_stats[league]["total"] += 1
        if ev.is_correct:
            league_stats[league]["correct"] += 1

    for s in league_stats.values():
        s["accuracy"] = s["correct"] / s["total"] if s["total"] > 0 else 0.0

    sorted_leagues = sorted(league_stats.values(), key=lambda x: x["accuracy"], reverse=True)
    best = [WeeklyPerformer(name=s["name"], accuracy=s["accuracy"], total=s["total"]) for s in sorted_leagues[:3]]
    worst = [WeeklyPerformer(name=s["name"], accuracy=s["accuracy"], total=s["total"]) for s in sorted_leagues[-3:]] if len(sorted_leagues) > 3 else []

    return WeeklySummaryResponse(
        total_calls=total_calls,
        won=won,
        lost=lost,
        win_rate=round(win_rate, 4),
        pl_units=round(pl_units, 2),
        best_performers=best,
        worst_performers=worst,
    )


@router.get(
    "/results",
    response_model=ResultsResponse,
    summary="Recent finished matches with scores and prediction evaluation",
    description=(
        "Returns finished matches from the last N days (default 7), "
        "including final scores and the latest model prediction for each "
        "match so accuracy can be assessed.  Data is refreshed continuously "
        "by the background sync tasks.\n\n"
        "**" + _SIMULATION_DISCLAIMER + "**"
    ),
)
async def get_results(
    days: int = Query(
        default=7,
        ge=1,
        le=90,
        description="How many days back to retrieve results (1–90).",
    ),
    league_slug: Optional[str] = Query(
        default=None, description="Filter by league slug."
    ),
    db: AsyncSession = Depends(get_db),
) -> ResultsResponse:
    now = datetime.now(timezone.utc)
    cutoff = now - timedelta(days=days)

    stmt = (
        select(Match)
        .where(
            and_(
                Match.status == MatchStatus.FINISHED,
                Match.scheduled_at >= cutoff,
                Match.scheduled_at <= now,
            )
        )
        .order_by(Match.scheduled_at.desc())
    )

    if league_slug:
        stmt = stmt.join(League, League.id == Match.league_id).where(
            League.slug == league_slug
        )

    raw_matches = (await db.execute(stmt)).scalars().all()
    matches = _dedup_fixtures(raw_matches)
    match_ids = [m.id for m in matches]
    pred_map = await _load_latest_predictions(match_ids, db)
    odds_map = await _load_latest_odds(match_ids, db)

    fixtures = [
        _build_fixture_item(m, pred_map.get(m.id), odds_map.get(m.id))
        for m in matches
    ]

    return ResultsResponse(days=days, count=len(fixtures), fixtures=fixtures)
