"""
Fixtures API Routes
====================
All routes in this module read ONLY from the local PostgreSQL database.
No external API calls are made.  Data is kept fresh by the background
``task_sync_matches`` Celery task which runs every 5 minutes.

Endpoints
---------
GET /fixtures/upcoming              – upcoming matches (+ predictions)
GET /fixtures/today                 – today's matches
GET /fixtures/results               – finished matches with scores (?days=7)
GET /fixtures/results/weekly-summary – weekly winners/losers stats

SIMULATION / EDUCATIONAL DISCLAIMER
-------------------------------------
All probability estimates provided on this platform are produced by a
statistical model for simulation and educational research purposes only.
They do NOT constitute financial, betting, or investment advice of any kind.
"""
from __future__ import annotations

from datetime import date, datetime, timedelta, timezone
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Depends, Query
from pydantic import BaseModel, ConfigDict, Field
from sqlalchemy import and_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import get_db
from app.models.league import League
from app.models.match import Match, MatchResult, MatchStatus
from app.models.prediction import Prediction
from app.models.team import Team

router = APIRouter()

_SIMULATION_DISCLAIMER = (
    "SIMULATION / EDUCATIONAL USE ONLY. "
    "All probability estimates are generated by a statistical model for "
    "research and educational purposes. They do NOT constitute financial, "
    "betting, or investment advice. Past model performance is not indicative "
    "of future results. Always gamble responsibly and within applicable laws."
)


# ─────────────────────────────────────────────────────────────────────────────
# Response schemas
# ─────────────────────────────────────────────────────────────────────────────


class PredictionSummary(BaseModel):
    """Slim prediction summary embedded in a fixture response."""

    model_config = ConfigDict(from_attributes=True)

    id: str
    home_win_prob: float
    draw_prob: Optional[float] = None
    away_win_prob: float
    predicted_home_score: Optional[float] = None
    predicted_away_score: Optional[float] = None
    confidence: float
    disclaimer: str = _SIMULATION_DISCLAIMER
    is_simulation: bool = True


class ResultSummary(BaseModel):
    """Score summary embedded in a fixture response."""

    home_score: int
    away_score: int
    home_score_ht: Optional[int] = None
    away_score_ht: Optional[int] = None
    winner: Optional[str] = None  # "home" | "away" | "draw"


class FixtureItem(BaseModel):
    """A single fixture row as returned by the /fixtures endpoints."""

    id: str
    league_id: str
    league_name: Optional[str] = None
    league_slug: Optional[str] = None
    home_team_id: str
    home_team_name: Optional[str] = None
    home_team_slug: Optional[str] = None
    away_team_id: str
    away_team_name: Optional[str] = None
    away_team_slug: Optional[str] = None
    external_id: Optional[str] = None
    status: str
    scheduled_at: datetime
    venue: Optional[str] = None
    round_name: Optional[str] = None
    matchday: Optional[int] = None
    result: Optional[ResultSummary] = None
    prediction: Optional[PredictionSummary] = None


class UpcomingFixturesResponse(BaseModel):
    """Response envelope for /fixtures/upcoming."""

    count: int
    disclaimer: str = _SIMULATION_DISCLAIMER
    fixtures: List[FixtureItem]


class TodayFixturesResponse(BaseModel):
    """Response envelope for /fixtures/today."""

    date: str
    count: int
    disclaimer: str = _SIMULATION_DISCLAIMER
    fixtures: List[FixtureItem]


class ResultsResponse(BaseModel):
    """Response envelope for /fixtures/results."""

    days: int
    count: int
    disclaimer: str = _SIMULATION_DISCLAIMER
    fixtures: List[FixtureItem]


class WeeklySummaryItem(BaseModel):
    """One team's performance entry in the weekly summary."""

    team_id: str
    team_name: Optional[str]
    team_slug: Optional[str]
    matches_played: int
    wins: int
    draws: int
    losses: int
    goals_for: int
    goals_against: int
    goal_difference: int
    points: int


class WeeklySummaryResponse(BaseModel):
    """Response envelope for /fixtures/results/weekly-summary."""

    week_start: str
    week_end: str
    total_matches: int
    disclaimer: str = _SIMULATION_DISCLAIMER
    top_teams: List[WeeklySummaryItem]
    bottom_teams: List[WeeklySummaryItem]


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────


def _build_fixture_item(
    match: Match,
    latest_prediction: Optional[Prediction] = None,
) -> FixtureItem:
    """Convert a Match ORM object to a FixtureItem response schema."""
    result_summary: Optional[ResultSummary] = None
    if match.result:
        result_summary = ResultSummary(
            home_score=match.result.home_score,
            away_score=match.result.away_score,
            home_score_ht=match.result.home_score_ht,
            away_score_ht=match.result.away_score_ht,
            winner=match.result.winner,
        )

    pred_summary: Optional[PredictionSummary] = None
    if latest_prediction:
        pred_summary = PredictionSummary(
            id=str(latest_prediction.id),
            home_win_prob=latest_prediction.home_win_prob,
            draw_prob=latest_prediction.draw_prob,
            away_win_prob=latest_prediction.away_win_prob,
            predicted_home_score=latest_prediction.predicted_home_score,
            predicted_away_score=latest_prediction.predicted_away_score,
            confidence=latest_prediction.confidence,
        )

    return FixtureItem(
        id=str(match.id),
        league_id=str(match.league_id),
        league_name=match.league.name if match.league else None,
        league_slug=match.league.slug if match.league else None,
        home_team_id=str(match.home_team_id),
        home_team_name=match.home_team.name if match.home_team else None,
        home_team_slug=match.home_team.slug if match.home_team else None,
        away_team_id=str(match.away_team_id),
        away_team_name=match.away_team.name if match.away_team else None,
        away_team_slug=match.away_team.slug if match.away_team else None,
        external_id=match.external_id,
        status=match.status.value if isinstance(match.status, MatchStatus) else str(match.status),
        scheduled_at=match.scheduled_at,
        venue=match.venue,
        round_name=match.round_name,
        matchday=match.matchday,
        result=result_summary,
        prediction=pred_summary,
    )


async def _load_latest_predictions(
    match_ids: list,
    db: AsyncSession,
) -> dict:
    """Return a {match_id: Prediction} mapping for the latest prediction per match."""
    if not match_ids:
        return {}

    # Subquery: max predicted_at per match_id
    from sqlalchemy import func
    subq = (
        select(
            Prediction.match_id,
            func.max(Prediction.predicted_at).label("latest_at"),
        )
        .where(Prediction.match_id.in_(match_ids))
        .group_by(Prediction.match_id)
        .subquery()
    )

    stmt = select(Prediction).join(
        subq,
        and_(
            Prediction.match_id == subq.c.match_id,
            Prediction.predicted_at == subq.c.latest_at,
        ),
    )
    rows = (await db.execute(stmt)).scalars().all()
    return {p.match_id: p for p in rows}


# ─────────────────────────────────────────────────────────────────────────────
# Routes
# ─────────────────────────────────────────────────────────────────────────────


@router.get(
    "/upcoming",
    response_model=UpcomingFixturesResponse,
    summary="Upcoming matches from the local DB with predictions",
    description=(
        "Returns all scheduled/upcoming matches stored in the database, "
        "enriched with the latest AI prediction where available.  "
        "Data is refreshed every 5 minutes by the background sync task.  "
        "No external API calls are made by this endpoint.\n\n"
        "**" + _SIMULATION_DISCLAIMER + "**"
    ),
)
async def get_upcoming_fixtures(
    days: int = Query(
        default=7,
        ge=1,
        le=30,
        description="How many days ahead to look for fixtures (1–30).",
    ),
    league_slug: Optional[str] = Query(
        default=None, description="Filter by league slug (e.g. 'premier-league')."
    ),
    db: AsyncSession = Depends(get_db),
) -> UpcomingFixturesResponse:
    now = datetime.now(timezone.utc)
    cutoff = now + timedelta(days=days)

    stmt = (
        select(Match)
        .where(
            and_(
                Match.status.in_([MatchStatus.SCHEDULED, MatchStatus.LIVE]),
                Match.scheduled_at >= now,
                Match.scheduled_at <= cutoff,
            )
        )
        .order_by(Match.scheduled_at)
    )

    if league_slug:
        stmt = stmt.join(League, League.id == Match.league_id).where(
            League.slug == league_slug
        )

    matches = (await db.execute(stmt)).scalars().all()
    match_ids = [m.id for m in matches]
    pred_map = await _load_latest_predictions(match_ids, db)

    fixtures = [
        _build_fixture_item(m, pred_map.get(m.id)) for m in matches
    ]

    return UpcomingFixturesResponse(count=len(fixtures), fixtures=fixtures)


@router.get(
    "/today",
    response_model=TodayFixturesResponse,
    summary="Today's matches from the local DB",
    description=(
        "Returns all matches scheduled for today (UTC), enriched with "
        "predictions.  Data is refreshed every 5 minutes.\n\n"
        "**" + _SIMULATION_DISCLAIMER + "**"
    ),
)
async def get_today_fixtures(
    db: AsyncSession = Depends(get_db),
) -> TodayFixturesResponse:
    today = date.today()
    day_start = datetime(today.year, today.month, today.day, tzinfo=timezone.utc)
    day_end = day_start + timedelta(days=1)

    stmt = (
        select(Match)
        .where(
            and_(
                Match.scheduled_at >= day_start,
                Match.scheduled_at < day_end,
            )
        )
        .order_by(Match.scheduled_at)
    )
    matches = (await db.execute(stmt)).scalars().all()
    match_ids = [m.id for m in matches]
    pred_map = await _load_latest_predictions(match_ids, db)

    fixtures = [
        _build_fixture_item(m, pred_map.get(m.id)) for m in matches
    ]

    return TodayFixturesResponse(
        date=today.isoformat(),
        count=len(fixtures),
        fixtures=fixtures,
    )


@router.get(
    "/results/weekly-summary",
    response_model=WeeklySummaryResponse,
    summary="Weekly winners/losers summary",
    description=(
        "Aggregates results from the last 7 days to rank teams by points "
        "earned in that period.  Returns the top 5 and bottom 5 performers."
    ),
)
async def get_weekly_summary(
    db: AsyncSession = Depends(get_db),
) -> WeeklySummaryResponse:
    from sqlalchemy import func

    now = datetime.now(timezone.utc)
    week_ago = now - timedelta(days=7)

    # Fetch all finished matches this week
    stmt = (
        select(Match)
        .where(
            and_(
                Match.status == MatchStatus.FINISHED,
                Match.scheduled_at >= week_ago,
                Match.scheduled_at <= now,
            )
        )
        .order_by(Match.scheduled_at)
    )
    matches = (await db.execute(stmt)).scalars().all()

    # Aggregate per team
    team_stats: dict[str, dict] = {}

    for m in matches:
        if m.result is None:
            continue

        home_id = str(m.home_team_id)
        away_id = str(m.away_team_id)

        for team_id, is_home in [(home_id, True), (away_id, False)]:
            if team_id not in team_stats:
                team_obj = m.home_team if is_home else m.away_team
                team_stats[team_id] = {
                    "team_id": team_id,
                    "team_name": team_obj.name if team_obj else None,
                    "team_slug": team_obj.slug if team_obj else None,
                    "matches_played": 0,
                    "wins": 0,
                    "draws": 0,
                    "losses": 0,
                    "goals_for": 0,
                    "goals_against": 0,
                    "goal_difference": 0,
                    "points": 0,
                }
            entry = team_stats[team_id]
            entry["matches_played"] += 1

            if is_home:
                gf = m.result.home_score
                ga = m.result.away_score
                winner = m.result.winner
                outcome = "home" if winner == "home" else ("draw" if winner == "draw" else "loss")
            else:
                gf = m.result.away_score
                ga = m.result.home_score
                winner = m.result.winner
                outcome = "away" if winner == "away" else ("draw" if winner == "draw" else "loss")

            entry["goals_for"] += gf
            entry["goals_against"] += ga
            entry["goal_difference"] = entry["goals_for"] - entry["goals_against"]

            if outcome in ("home", "away"):
                entry["wins"] += 1
                entry["points"] += 3
            elif outcome == "draw":
                entry["draws"] += 1
                entry["points"] += 1
            else:
                entry["losses"] += 1

    ranked = sorted(
        team_stats.values(),
        key=lambda t: (t["points"], t["goal_difference"], t["goals_for"]),
        reverse=True,
    )

    top = [WeeklySummaryItem(**t) for t in ranked[:5]]
    bottom = [WeeklySummaryItem(**t) for t in ranked[-5:]] if len(ranked) >= 5 else []

    return WeeklySummaryResponse(
        week_start=week_ago.date().isoformat(),
        week_end=now.date().isoformat(),
        total_matches=len(matches),
        top_teams=top,
        bottom_teams=bottom,
    )


@router.get(
    "/results",
    response_model=ResultsResponse,
    summary="Recent finished matches with scores and prediction evaluation",
    description=(
        "Returns finished matches from the last N days (default 7), "
        "including final scores and the latest model prediction for each "
        "match so accuracy can be assessed.  Data is refreshed continuously "
        "by the background sync tasks.\n\n"
        "**" + _SIMULATION_DISCLAIMER + "**"
    ),
)
async def get_results(
    days: int = Query(
        default=7,
        ge=1,
        le=90,
        description="How many days back to retrieve results (1–90).",
    ),
    league_slug: Optional[str] = Query(
        default=None, description="Filter by league slug."
    ),
    db: AsyncSession = Depends(get_db),
) -> ResultsResponse:
    now = datetime.now(timezone.utc)
    cutoff = now - timedelta(days=days)

    stmt = (
        select(Match)
        .where(
            and_(
                Match.status == MatchStatus.FINISHED,
                Match.scheduled_at >= cutoff,
                Match.scheduled_at <= now,
            )
        )
        .order_by(Match.scheduled_at.desc())
    )

    if league_slug:
        stmt = stmt.join(League, League.id == Match.league_id).where(
            League.slug == league_slug
        )

    matches = (await db.execute(stmt)).scalars().all()
    match_ids = [m.id for m in matches]
    pred_map = await _load_latest_predictions(match_ids, db)

    fixtures = [
        _build_fixture_item(m, pred_map.get(m.id)) for m in matches
    ]

    return ResultsResponse(days=days, count=len(fixtures), fixtures=fixtures)
