"""Strategy API routes."""
from __future__ import annotations

import uuid
from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import aliased

from app.api.deps import get_current_tier
from app.core.prediction_filters import trackrecord_filter
from app.core.tier_system import (
    PickTier,
    TIER_SYSTEM_ENABLED,
    access_filter,
)
from app.db.session import get_db
from app.models.league import League
from app.models.match import Match
from app.models.odds import OddsHistory
from app.models.prediction import Prediction
from app.models.strategy import Strategy
from app.models.team import Team
from app.schemas.strategy import (
    StrategyPickPrediction,
    StrategyPicksResponse,
    StrategyResponse,
)
from app.services.strategy_engine import evaluate_strategy

router = APIRouter()


# ──────────────────────────────────────────────────────────────────────────────
# Odds bulk-loader
# ──────────────────────────────────────────────────────────────────────────────
async def _load_odds_map(
    match_ids: list[uuid.UUID], db: AsyncSession
) -> dict[uuid.UUID, dict]:
    """Bulk-load latest 1X2 odds rows keyed by match_id.

    Strategy evaluators run in strict mode and reject rules whose feature
    returns None. Without odds loaded, every odds-based rule (edge_pick,
    odds_home, ...) silently fails — so a strategy like "edge >= 5%" can
    never match a single pick. This helper hydrates a map of the latest
    odds row per match in a single query, which the eval loop can then
    pass into ``evaluate_strategy(..., odds=odds_map.get(match_id))``.

    Returns ``{}`` when ``match_ids`` is empty.
    """
    if not match_ids:
        return {}
    stmt = (
        select(OddsHistory)
        .where(
            OddsHistory.match_id.in_(match_ids),
            OddsHistory.market.in_(["1x2", "1X2"]),
        )
        .order_by(OddsHistory.match_id, OddsHistory.recorded_at.desc())
    )
    rows = (await db.execute(stmt)).scalars().all()
    odds_map: dict[uuid.UUID, dict] = {}
    for row in rows:
        # First row per match wins (DESC order = latest recorded). Skip
        # subsequent rows for the same match.
        if row.match_id in odds_map:
            continue
        odds_map[row.match_id] = {
            "home_odds": row.home_odds,
            "draw_odds": row.draw_odds,
            "away_odds": row.away_odds,
        }
    return odds_map


# ──────────────────────────────────────────────────────────────────────────────
# Validation status — conservative plausibility gates
# ──────────────────────────────────────────────────────────────────────────────
#
# The numbers reported by this endpoint are computed on predictions generated by
# the current ensemble forecast model. As of 2026-04-11, that model has a known
# feature-leakage issue: the EloModel is instantiated fresh per prediction and
# seeds its ratings from ``app/forecasting/team_seeds.py``, a hand-curated table
# of "current-day" Elo values. When the sync job or ``admin_backfill`` generates
# predictions for historical fixtures, the seeds are still the same static
# present-day numbers — so the model is effectively using post-hoc knowledge of
# which teams turned out to be strong. That inflates strike rates far above what
# any real 1X2 model can achieve.
#
# A well-calibrated 1X2 model on European top-five + Eredivisie caps out around
# 53-56% strike rate and 1-5% ROI after commission. Anything materially above
# those numbers on samples of a few hundred picks is virtually certain to be a
# data-quality artefact, not an edge. We therefore gate strategies with the
# following honest criteria, which take effect on every ``/metrics`` call and
# every ``/validation-refresh`` run:
#
#   * sample_size < 30                 → "insufficient_data"
#   * winrate > 0.58                   → "under_investigation"
#       (implausibly high without leakage, regardless of ROI)
#   * roi > 0.08                       → "under_investigation"
#       (implausibly high ROI for a flat-odds 1X2 strategy)
#   * roi < -0.02                      → "rejected"
#   * otherwise, roi > 0.02            → "validated"
#   * otherwise                        → "break_even"
#
# These are deliberately blunt. They are a tripwire, not a substitute for a
# proper walk-forward / bootstrap validation pipeline — but they will prevent
# the frontend from confidently displaying impossible ROIs while the underlying
# Elo leakage is being fixed.

_LEAKAGE_WINRATE_CEILING = 0.58
_LEAKAGE_ROI_CEILING = 0.08

# v5.3: walk-forward-based validation thresholds. These replace the
# winrate / roi ceilings as the primary signal once walk-forward data
# is available for a strategy.
_WF_MIN_SAMPLE = 100
_WF_MIN_POSITIVE_RATIO = 0.60     # ≥ 60% of rolling test windows positive
_WF_MIN_SHARPE = 1.0              # sharpe floor for "validated"
_WF_MIN_MEAN_ROI = 0.02           # mean test ROI must exceed +2%
_WF_MIN_ODDS_COVERAGE_PCT = 30.0  # at least 30% of picks have real odds


def _compute_walk_forward_status(
    sample_size: int,
    winrate: float,
    roi: float,
    odds_coverage_pct: float,
    wf: Optional[dict],
) -> tuple[str, str]:
    """v5.3 validation logic that uses walk-forward metrics as the
    primary signal and falls back to the v5.0 winrate/ROI gates when
    walk-forward data is not available.

    Decision tree:
      1. sample_size < 30 → insufficient_data
      2. wf is None or wf.total_windows == 0 → fall back to v5.0 gate
      3. wf.total_windows >= 3 AND wf.positive_windows_ratio >= 0.6
         AND wf.sharpe >= 1.0 AND wf.mean_test_roi >= 0.02
         AND odds_coverage_pct >= 30% → validated
      4. wf.mean_test_roi < -0.02 → rejected
      5. winrate > 58% or roi > 8% (v5.0 implausibility ceilings)
         AND odds_coverage_pct < 30% → under_investigation
      6. roi > 0.02 → break_even_promising
      7. otherwise → break_even
    """
    if sample_size < 30:
        return (
            "insufficient_data",
            f"Only {sample_size} picks — need ≥30 before we trust any number.",
        )

    # If walk-forward data exists, use it as the primary signal.
    if wf is not None and wf.get("total_windows", 0) >= 3:
        ratio = float(wf.get("positive_windows_ratio") or 0.0)
        sharpe = float(wf.get("sharpe") or 0.0)
        mean_roi = float(wf.get("mean_test_roi") or 0.0)

        if mean_roi < -0.02:
            return (
                "rejected",
                f"Walk-forward mean ROI {mean_roi:+.1%} is materially negative "
                f"over {wf['total_windows']} rolling windows.",
            )

        if (
            ratio >= _WF_MIN_POSITIVE_RATIO
            and sharpe >= _WF_MIN_SHARPE
            and mean_roi >= _WF_MIN_MEAN_ROI
            and odds_coverage_pct >= _WF_MIN_ODDS_COVERAGE_PCT
        ):
            return (
                "validated",
                f"Walk-forward: {wf['positive_windows']}/{wf['total_windows']} "
                f"positive windows, Sharpe {sharpe:.2f}, mean ROI {mean_roi:+.1%}, "
                f"real-odds coverage {odds_coverage_pct:.0f}%.",
            )

        # Consistently positive but missing odds coverage or threshold.
        if (
            ratio >= _WF_MIN_POSITIVE_RATIO
            and sharpe >= _WF_MIN_SHARPE
            and mean_roi >= _WF_MIN_MEAN_ROI
            and odds_coverage_pct < _WF_MIN_ODDS_COVERAGE_PCT
        ):
            return (
                "under_investigation",
                f"Walk-forward looks strong ({wf['positive_windows']}/{wf['total_windows']} "
                f"positive, Sharpe {sharpe:.2f}), but real-odds coverage is only "
                f"{odds_coverage_pct:.0f}% — ROI math still relies on the 1.90 "
                f"fallback. Re-check after the odds snapshot cron has run for 2+ weeks.",
            )

        if mean_roi >= _WF_MIN_MEAN_ROI:
            return (
                "under_investigation",
                f"Walk-forward mean ROI {mean_roi:+.1%} is positive but the pattern "
                f"isn't robust: {wf['positive_windows']}/{wf['total_windows']} positive "
                f"windows, Sharpe {sharpe:.2f}. Needs more data or tighter rule.",
            )

        if abs(mean_roi) <= 0.02:
            return (
                "break_even",
                f"Walk-forward mean ROI {mean_roi:+.1%} is within the ±2% break-even band.",
            )

        # Negative but not extreme.
        return (
            "rejected",
            f"Walk-forward mean ROI {mean_roi:+.1%} is negative.",
        )

    # Fallback to the v5.0 gate when walk-forward data is not available
    # (e.g. sample too small for windows, or walk-forward wasn't run).
    return _compute_validation_status(sample_size, winrate, roi)


def _compute_validation_status(
    sample_size: int, winrate: float, roi: float
) -> tuple[str, str]:
    """Return (status, notes) for a given set of computed metrics.

    Notes explain *why* the status was assigned, so the frontend can surface a
    tooltip or badge. See module docstring above for the exact criteria.
    """
    if sample_size < 30:
        return (
            "insufficient_data",
            f"Only {sample_size} picks — need ≥30 before we trust any number.",
        )
    if winrate > _LEAKAGE_WINRATE_CEILING:
        return (
            "under_investigation",
            (
                f"Strike rate of {winrate:.1%} exceeds the {_LEAKAGE_WINRATE_CEILING:.0%} "
                "plausibility ceiling for 1X2. Likely feature leakage from the "
                "static team_seeds.py Elo table — metrics pending rebuild with "
                "point-in-time ratings."
            ),
        )
    if roi > _LEAKAGE_ROI_CEILING:
        return (
            "under_investigation",
            (
                f"ROI of {roi:+.1%} exceeds the {_LEAKAGE_ROI_CEILING:+.0%} plausibility "
                "ceiling for 1X2 at flat 1.90 odds. Treat as a data artefact until "
                "validated with real historical odds and point-in-time features."
            ),
        )
    if roi < -0.02:
        return (
            "rejected",
            f"ROI of {roi:+.1%} is materially negative — strategy does not beat the vig.",
        )
    if roi > 0.02:
        return (
            "validated",
            f"ROI {roi:+.1%} on {sample_size} picks is within the plausible range for a real edge.",
        )
    return (
        "break_even",
        f"ROI {roi:+.1%} is within the break-even band; no reliable signal yet.",
    )


@router.get(
    "/",
    response_model=List[StrategyResponse],
    summary="List all strategies",
)
async def list_strategies(
    active_only: bool = Query(default=False, description="Return only active strategies"),
    db: AsyncSession = Depends(get_db),
) -> List[StrategyResponse]:
    """Return all strategies ordered by creation date."""
    q = select(Strategy).order_by(Strategy.created_at.desc())
    if active_only:
        q = q.where(Strategy.is_active.is_(True))

    result = await db.execute(q)
    strategies = result.scalars().all()
    return [StrategyResponse.model_validate(s) for s in strategies]


@router.get(
    "/{strategy_id}",
    response_model=StrategyResponse,
    summary="Get a single strategy",
)
async def get_strategy(
    strategy_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
) -> StrategyResponse:
    """Return a single strategy by ID."""
    result = await db.execute(
        select(Strategy).where(Strategy.id == strategy_id)
    )
    strategy = result.scalar_one_or_none()
    if strategy is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Strategy {strategy_id} not found.",
        )
    return StrategyResponse.model_validate(strategy)


@router.get(
    "/{strategy_id}/picks",
    response_model=StrategyPicksResponse,
    summary="Get predictions matching a strategy",
)
async def get_strategy_picks(
    strategy_id: uuid.UUID,
    limit: int = Query(default=50, ge=1, le=200, description="Max picks to return"),
    offset: int = Query(default=0, ge=0, description="Pagination offset"),
    db: AsyncSession = Depends(get_db),
    user_tier: PickTier = Depends(get_current_tier),
) -> StrategyPicksResponse:
    """
    Evaluate all recent predictions against the strategy and return matching picks.

    Predictions are evaluated in-memory against the strategy rules. Odds-based
    rules are skipped when odds data is not available.

    Tier-scoped: under ``TIER_SYSTEM_ENABLED`` rows are restricted to picks
    the caller's subscription tier can access — same rule as
    ``/{id}/today-picks``. Without this gate a Free user hitting the
    historical ``/picks`` endpoint would see Platinum-scope predictions
    that the paid-tier funnel is supposed to gate out.
    """
    # Fetch the strategy
    strat_result = await db.execute(
        select(Strategy).where(Strategy.id == strategy_id)
    )
    strategy = strat_result.scalar_one_or_none()
    if strategy is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Strategy {strategy_id} not found.",
        )

    # Fetch predictions with match context + evaluation
    from app.models.prediction import PredictionEvaluation
    from app.models.match import MatchResult, MatchStatus as MS

    HomeTeam = aliased(Team)
    AwayTeam = aliased(Team)

    q = (
        select(
            Prediction,
            Match.scheduled_at,
            Match.status.label("match_status"),
            HomeTeam.name.label("home_team_name"),
            AwayTeam.name.label("away_team_name"),
            HomeTeam.logo_url.label("home_team_logo"),
            AwayTeam.logo_url.label("away_team_logo"),
            League.name.label("league_name"),
            PredictionEvaluation.actual_outcome,
            PredictionEvaluation.is_correct,
            MatchResult.home_score,
            MatchResult.away_score,
        )
        .join(Match, Match.id == Prediction.match_id)
        .join(HomeTeam, HomeTeam.id == Match.home_team_id)
        .join(AwayTeam, AwayTeam.id == Match.away_team_id)
        .join(League, League.id == Match.league_id)
        .outerjoin(PredictionEvaluation, PredictionEvaluation.prediction_id == Prediction.id)
        .outerjoin(MatchResult, MatchResult.match_id == Match.id)
        # H7: align /picks with /metrics — only show pre-kickoff v8.1 picks.
        # Without this, post-kickoff backfill rows leak into the equity curve
        # while the headline numbers are filtered, producing two universes
        # on the same page.
        .where(trackrecord_filter())
        .order_by(Match.scheduled_at.desc())
    )
    if TIER_SYSTEM_ENABLED:
        q = q.where(access_filter(user_tier))

    result = await db.execute(q)
    rows = result.all()

    # H2: bulk-load 1X2 odds for every match in the candidate set so
    # odds-based rules (edge_pick, odds_home, ...) can evaluate. Without
    # this, strict-mode evaluation rejects every pick whose strategy
    # mentions odds and the equity curve is silently empty.
    odds_map = await _load_odds_map(
        list({row[0].match_id for row in rows}), db
    )
    from app.services.roi_calculator import realised_pnl_1x2

    # Evaluate each prediction against strategy rules
    matched_picks: list[StrategyPickPrediction] = []
    for row in rows:
        prediction = row[0]
        scheduled_at = row[1]
        match_status = row[2]
        home_team_name = row[3]
        away_team_name = row[4]
        home_team_logo = row[5]
        away_team_logo = row[6]
        league_name = row[7]
        actual_outcome = row[8]
        is_correct = row[9]
        home_score = row[10]
        away_score = row[11]

        odds = odds_map.get(prediction.match_id)
        if evaluate_strategy(strategy, prediction, odds):
            # Determine pick
            probs = {"HOME": prediction.home_win_prob, "DRAW": prediction.draw_prob or 0, "AWAY": prediction.away_win_prob}
            pick = max(probs, key=lambda k: probs[k])

            # H8: compute P/L from real historical odds (or null when
            # no odds row exists). The old hardcoded `0.9 / -1.0` was a
            # flat-1.90 fallback that contradicted the real-odds ROI
            # in /metrics — equity curve and headline numbers now
            # share the same odds universe.
            pnl: Optional[float] = None
            if is_correct is not None and actual_outcome is not None:
                computed_pnl, _, _ = await realised_pnl_1x2(
                    prediction=prediction,
                    actual_outcome=actual_outcome,
                    is_correct=bool(is_correct),
                    db=db,
                )
                pnl = computed_pnl

            status_str = match_status.value if hasattr(match_status, "value") else str(match_status)

            matched_picks.append(
                StrategyPickPrediction(
                    id=prediction.id,
                    match_id=prediction.match_id,
                    predicted_at=prediction.predicted_at,
                    home_win_prob=prediction.home_win_prob,
                    draw_prob=prediction.draw_prob,
                    away_win_prob=prediction.away_win_prob,
                    confidence=prediction.confidence,
                    prediction_type=prediction.prediction_type,
                    pick=pick,
                    home_team_name=home_team_name,
                    away_team_name=away_team_name,
                    home_team_logo=home_team_logo,
                    away_team_logo=away_team_logo,
                    scheduled_at=scheduled_at,
                    league_name=league_name,
                    match_status=status_str,
                    actual_outcome=actual_outcome,
                    is_correct=is_correct,
                    home_score=home_score,
                    away_score=away_score,
                    pnl=pnl,
                )
            )

    total = len(matched_picks)
    paginated = matched_picks[offset : offset + limit]

    return StrategyPicksResponse(
        strategy=StrategyResponse.model_validate(strategy),
        total=total,
        picks=paginated,
    )


@router.get(
    "/{strategy_id}/today-picks",
    summary="Get upcoming matches that match this strategy",
)
async def get_strategy_today_picks(
    strategy_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    user_tier: PickTier = Depends(get_current_tier),
):
    """Return upcoming scheduled matches that pass this strategy's filters (tier-scoped)."""
    from app.core.cache import cache_get, cache_set
    from datetime import datetime, timedelta, timezone
    from app.models.match import MatchStatus

    # Check cache — tier-aware key
    cache_key = f"strategy:today:{strategy_id}:{user_tier.name.lower()}"
    cached = await cache_get(cache_key)
    if cached is not None:
        return cached

    # Get strategy
    strat_result = await db.execute(select(Strategy).where(Strategy.id == strategy_id))
    strategy = strat_result.scalar_one_or_none()
    if strategy is None:
        raise HTTPException(status_code=404, detail="Strategy not found")

    # Get upcoming predictions
    now = datetime.now(timezone.utc)
    cutoff = now + timedelta(hours=72)

    HomeTeam = aliased(Team)
    AwayTeam = aliased(Team)

    q = (
        select(
            Prediction,
            Match.scheduled_at,
            HomeTeam.name.label("home"),
            AwayTeam.name.label("away"),
            HomeTeam.logo_url.label("home_logo"),
            AwayTeam.logo_url.label("away_logo"),
            League.name.label("league"),
        )
        .join(Match, Match.id == Prediction.match_id)
        .join(HomeTeam, HomeTeam.id == Match.home_team_id)
        .join(AwayTeam, AwayTeam.id == Match.away_team_id)
        .join(League, League.id == Match.league_id)
        .where(
            Match.status == MatchStatus.SCHEDULED,
            Match.scheduled_at >= now,
            Match.scheduled_at <= cutoff,
        )
        .order_by(Match.scheduled_at)
    )
    # v8.1 tier access filter
    if TIER_SYSTEM_ENABLED:
        q = q.where(access_filter(user_tier))
    rows = (await db.execute(q)).all()

    # H2: hydrate odds so odds-based strategy rules can match.
    odds_map = await _load_odds_map([r[0].match_id for r in rows], db)

    picks = []
    for pred, scheduled_at, home, away, home_logo, away_logo, league in rows:
        if evaluate_strategy(strategy, pred, odds=odds_map.get(pred.match_id)):
            probs = {
                "HOME": pred.home_win_prob,
                "DRAW": pred.draw_prob or 0,
                "AWAY": pred.away_win_prob,
            }
            pick = max(probs, key=lambda k: probs[k])
            picks.append(
                {
                    "match_id": str(pred.match_id),
                    "home_team": home,
                    "away_team": away,
                    "home_team_logo": home_logo,
                    "away_team_logo": away_logo,
                    "league": league,
                    "kickoff": scheduled_at.isoformat(),
                    "pick": pick,
                    "home_win_prob": round(pred.home_win_prob, 4),
                    "draw_prob": round(pred.draw_prob or 0, 4),
                    "away_win_prob": round(pred.away_win_prob, 4),
                    "confidence": round(pred.confidence, 4),
                }
            )

    result = {
        "strategy_name": strategy.name,
        "picks_count": len(picks),
        "picks": picks,
    }
    await cache_set(cache_key, result, ttl=600)  # 10 min cache
    return result


@router.get(
    "/{strategy_id}/metrics",
    summary="Get performance metrics for a strategy",
)
async def get_strategy_metrics(
    strategy_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    user_tier: PickTier = Depends(get_current_tier),
):
    """
    Calculate performance metrics for a strategy based on evaluated predictions.
    Results are cached in Redis for 15 minutes (per-tier).
    Returns: sample_size, winrate, roi, max_drawdown, profit_factor.
    """
    from app.core.cache import cache_get, cache_set
    from app.models.prediction import PredictionEvaluation

    # Check cache first — tier-aware key
    cache_key = f"strategy:metrics:{strategy_id}:{user_tier.name.lower()}"
    cached = await cache_get(cache_key)
    if cached is not None:
        return cached

    # Fetch strategy
    strat_result = await db.execute(select(Strategy).where(Strategy.id == strategy_id))
    strategy = strat_result.scalar_one_or_none()
    if strategy is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Strategy not found")

    # Get all evaluated predictions
    HomeTeam = aliased(Team)
    AwayTeam = aliased(Team)

    q = (
        select(Prediction, PredictionEvaluation)
        .join(Match, Match.id == Prediction.match_id)
        .join(PredictionEvaluation, PredictionEvaluation.prediction_id == Prediction.id)
        .join(HomeTeam, HomeTeam.id == Match.home_team_id)
        .join(AwayTeam, AwayTeam.id == Match.away_team_id)
        .join(League, League.id == Match.league_id)
        # v8.1 filter: exclude pre-deploy predictions (broken feature pipeline)
        .where(trackrecord_filter())
        .order_by(Match.scheduled_at)
    )
    # v8.1 tier access filter
    if TIER_SYSTEM_ENABLED:
        q = q.where(access_filter(user_tier))
    rows = (await db.execute(q)).all()

    # H2: hydrate odds so edge / odds-based rules can match.
    odds_map = await _load_odds_map(
        list({pred.match_id for pred, _ in rows}), db
    )

    # Filter for strategy matches
    matched_and_evaluated = []
    for pred, evaluation in rows:
        if evaluate_strategy(strategy, pred, odds=odds_map.get(pred.match_id)):
            matched_and_evaluated.append((pred, evaluation))

    sample_size = len(matched_and_evaluated)
    if sample_size == 0:
        return {
            "strategy_id": str(strategy_id),
            "strategy_name": strategy.name,
            "sample_size": 0,
            "winrate": 0.0,
            "roi": 0.0,
            "max_drawdown": 0.0,
            "profit_factor": 0.0,
            "avg_brier": 0.0,
            "odds_coverage_pct": 0.0,
            "avg_odds_used": 0.0,
            "has_data": False,
            "validation_status": "insufficient_data",
            "validation_notes": "No evaluated predictions yet for this strategy.",
        }

    # v5: use real historical odds from odds_history when available.
    # Falls back to 1.90 flat for picks with no odds row.
    from app.services.roi_calculator import compute_strategy_metrics_with_real_odds
    metrics = await compute_strategy_metrics_with_real_odds(
        picks=matched_and_evaluated,
        db=db,
    )
    winrate = metrics["winrate"]
    roi = metrics["roi"]
    correct = metrics["wins"]
    losses = metrics["losses"]

    avg_brier = sum(
        (ev.brier_score or 0.0) for _, ev in matched_and_evaluated
    ) / sample_size

    validation_status, validation_notes = _compute_validation_status(
        sample_size=sample_size, winrate=winrate, roi=roi
    )

    # For strategies flagged as under_investigation we deliberately clamp the
    # displayed numbers so downstream clients (e.g. the current frontend
    # which renders a "Profitable" badge from ``roi > 0``) don't show glowing
    # metrics while the underlying feature leakage is still being fixed. The
    # *raw* computed numbers are preserved under ``raw_winrate`` / ``raw_roi``
    # so the upcoming strategy-lab rebuild can still show them behind a
    # "disputed" treatment.
    raw_winrate = round(winrate, 4)
    raw_roi = round(roi, 4)
    if validation_status == "under_investigation":
        display_winrate = 0.0
        display_roi = 0.0
    else:
        display_winrate = raw_winrate
        display_roi = raw_roi

    result = {
        "strategy_id": str(strategy_id),
        "strategy_name": strategy.name,
        "sample_size": sample_size,
        # ``winrate`` / ``roi`` carry the DISPLAY values (zeroed for suspicious
        # strategies). Existing frontend code reading these fields will stop
        # labelling them as profitable.
        "winrate": display_winrate,
        "roi": display_roi,
        "raw_winrate": raw_winrate,
        "raw_roi": raw_roi,
        "max_drawdown": metrics["max_drawdown"],
        "profit_factor": metrics["profit_factor"],
        "avg_brier": round(avg_brier, 6),
        "correct": correct,
        "incorrect": losses,
        "has_data": True,
        # v5 additions — see API_CONTRACT.md for semantics.
        "validation_status": validation_status,
        "validation_notes": validation_notes,
        "odds_coverage_pct": metrics["odds_coverage_pct"],
        "avg_odds_used": metrics["avg_odds_used"],
    }

    # Cache for 15 minutes
    await cache_set(cache_key, result, ttl=900)
    return result


async def _walk_forward_for_strategy(
    strategy: Strategy,
    train_days: int,
    test_days: int,
    db: AsyncSession,
    pre_fetched_rows: Optional[list] = None,
) -> dict:
    """Pure helper that runs walk-forward for a single strategy.

    Used by both ``GET /{id}/walk-forward`` (single) and the new
    ``GET /walk-forward-all`` (batch). When called from the batch
    endpoint, ``pre_fetched_rows`` avoids re-querying all
    Prediction+Evaluation rows for every strategy.
    """
    import statistics
    from datetime import timedelta as _td
    from app.models.prediction import PredictionEvaluation
    from app.services.roi_calculator import realised_pnl_1x2

    if pre_fetched_rows is None:
        q = (
            select(Prediction, PredictionEvaluation, Match.scheduled_at)
            .join(Match, Match.id == Prediction.match_id)
            .join(PredictionEvaluation, PredictionEvaluation.prediction_id == Prediction.id)
            # v8.1 filter
            .where(trackrecord_filter())
            .order_by(Match.scheduled_at.asc())
        )
        rows = (await db.execute(q)).all()
    else:
        rows = pre_fetched_rows

    # H2: hydrate odds for the entire walk-forward universe so odds-based
    # strategy rules can match across all folds. Walk-forward needs a
    # reasonable sample to be statistically meaningful, and odds=None
    # silently emptied the pool for any strategy mentioning edge_pick.
    odds_map = await _load_odds_map(
        list({pred.match_id for pred, _, _ in rows}), db
    )
    matched: list[tuple] = []
    for pred, evaluation, sched in rows:
        if evaluate_strategy(
            strategy, pred, odds=odds_map.get(pred.match_id)
        ):
            matched.append((pred, evaluation, sched))

    if len(matched) < 30:
        return {
            "strategy_id": str(strategy.id),
            "strategy_name": strategy.name,
            "sample_size": len(matched),
            "total_windows": 0,
            "positive_windows": 0,
            "mean_test_roi": 0.0,
            "std_test_roi": 0.0,
            "sharpe": 0.0,
            "windows": [],
            "reason": "insufficient_data_for_walk_forward",
        }

    picks_with_pnl: list[tuple[datetime, bool, float]] = []
    for pred, evaluation, sched in matched:
        pnl, _odds, _src = await realised_pnl_1x2(
            prediction=pred,
            actual_outcome=evaluation.actual_outcome,
            is_correct=bool(evaluation.is_correct),
            db=db,
        )
        picks_with_pnl.append((sched, bool(evaluation.is_correct), pnl))

    if not picks_with_pnl:
        return {
            "strategy_id": str(strategy.id),
            "strategy_name": strategy.name,
            "sample_size": 0,
            "total_windows": 0,
            "positive_windows": 0,
            "mean_test_roi": 0.0,
            "std_test_roi": 0.0,
            "sharpe": 0.0,
            "windows": [],
            "reason": "no_pnl_data",
        }

    earliest = min(p[0] for p in picks_with_pnl)
    latest = max(p[0] for p in picks_with_pnl)

    window_start = earliest + _td(days=train_days)
    windows: list[dict] = []
    while window_start + _td(days=test_days) <= latest + _td(days=1):
        window_end = window_start + _td(days=test_days)
        win_picks = [
            (sched, correct, pnl)
            for sched, correct, pnl in picks_with_pnl
            if window_start <= sched < window_end
        ]
        n = len(win_picks)
        if n > 0:
            wins = sum(1 for _, c, _ in win_picks if c)
            total_pnl = sum(pnl for _, _, pnl in win_picks)
            windows.append({
                "test_start": window_start.isoformat(),
                "test_end": window_end.isoformat(),
                "n": n,
                "winrate": round(wins / n, 4),
                "roi": round(total_pnl / n, 4),
            })
        window_start = window_end

    if not windows:
        return {
            "strategy_id": str(strategy.id),
            "strategy_name": strategy.name,
            "sample_size": len(picks_with_pnl),
            "total_windows": 0,
            "positive_windows": 0,
            "mean_test_roi": 0.0,
            "std_test_roi": 0.0,
            "sharpe": 0.0,
            "windows": [],
            "reason": "no_test_windows_in_range",
        }

    roi_values = [w["roi"] for w in windows]
    mean_roi = statistics.fmean(roi_values)
    std_roi = statistics.pstdev(roi_values) if len(roi_values) > 1 else 0.0
    positive = sum(1 for r in roi_values if r > 0)
    sharpe = (
        (mean_roi / std_roi) * (len(roi_values) ** 0.5)
        if std_roi > 0
        else 0.0
    )

    return {
        "strategy_id": str(strategy.id),
        "strategy_name": strategy.name,
        "sample_size": len(picks_with_pnl),
        "train_days": train_days,
        "test_days": test_days,
        "total_windows": len(windows),
        "positive_windows": positive,
        "positive_windows_ratio": round(positive / len(windows), 4) if windows else 0.0,
        "mean_test_roi": round(mean_roi, 4),
        "std_test_roi": round(std_roi, 4),
        "sharpe": round(sharpe, 4),
        "windows": windows,
    }


@router.get(
    "/all/walk-forward",
    summary="Walk-forward validation for every strategy, ranked by Sharpe",
)
async def walk_forward_all(
    train_days: int = Query(default=28, ge=7, le=120),
    test_days: int = Query(default=14, ge=1, le=30),
    db: AsyncSession = Depends(get_db),
):
    """Run walk-forward validation for every strategy in one call and
    return a ranked list. Ranking is primarily by Sharpe (consistency)
    and secondarily by positive_windows_ratio.

    This is the v5.3 replacement for the winrate-based plausibility
    gate: a strategy with 63% winrate but 37/37 positive windows is
    far more trustworthy than one with 55% winrate but 15/30
    positive windows. Gate logic in ``_compute_validation_status``
    is updated to use these metrics.

    Heavy: pre-fetches all Prediction+Evaluation rows ONCE and reuses
    them across strategies. For ~5 000 picks × 15 strategies this
    comes in under Railway's 180s timeout.
    """
    from app.models.prediction import PredictionEvaluation
    import statistics

    pre_fetch_stmt = (
        select(Prediction, PredictionEvaluation, Match.scheduled_at)
        .join(Match, Match.id == Prediction.match_id)
        .join(PredictionEvaluation, PredictionEvaluation.prediction_id == Prediction.id)
        # v8.1 filter: restrict walk-forward to v8.1 predictions
        .where(trackrecord_filter())
        .order_by(Match.scheduled_at.asc())
    )
    pre_fetched = (await db.execute(pre_fetch_stmt)).all()

    strategies_stmt = select(Strategy).order_by(Strategy.name)
    strategies = list((await db.execute(strategies_stmt)).scalars().all())

    results: list[dict] = []
    for strat in strategies:
        result = await _walk_forward_for_strategy(
            strategy=strat,
            train_days=train_days,
            test_days=test_days,
            db=db,
            pre_fetched_rows=pre_fetched,
        )
        # Drop the full windows list to keep the payload small.
        # Callers can hit /{id}/walk-forward for per-window details.
        result_slim = {k: v for k, v in result.items() if k != "windows"}
        results.append(result_slim)

    # Rank by: positive_windows_ratio desc, then Sharpe desc, then mean_roi desc
    ranked = sorted(
        results,
        key=lambda r: (
            r.get("positive_windows_ratio", 0.0),
            r.get("sharpe", 0.0),
            r.get("mean_test_roi", 0.0),
        ),
        reverse=True,
    )

    return {
        "train_days": train_days,
        "test_days": test_days,
        "total_strategies": len(ranked),
        "ranked": ranked,
    }


@router.get(
    "/{strategy_id}/walk-forward",
    summary="Rolling train/test walk-forward validation over the full history",
)
async def walk_forward_strategy(
    strategy_id: uuid.UUID,
    train_days: int = Query(default=28, ge=7, le=120),
    test_days: int = Query(default=7, ge=1, le=30),
    db: AsyncSession = Depends(get_db),
):
    """Proper ML-style walk-forward validation for a single strategy.

    Delegates to ``_walk_forward_for_strategy`` so the logic stays in
    one place. The single-strategy endpoint returns the full window
    list; the batch endpoint (``/walk-forward-all``) strips it to
    keep the payload small.
    """
    strat_result = await db.execute(select(Strategy).where(Strategy.id == strategy_id))
    strategy = strat_result.scalar_one_or_none()
    if strategy is None:
        raise HTTPException(status_code=404, detail="Strategy not found")
    return await _walk_forward_for_strategy(
        strategy=strategy,
        train_days=train_days,
        test_days=test_days,
        db=db,
    )


@router.post(
    "/validation-refresh-v2",
    summary="v5.3 refresh: walk-forward is primary signal, then gate",
)
async def refresh_strategy_validation_v2(
    train_days: int = Query(default=28, ge=7, le=120),
    test_days: int = Query(default=14, ge=1, le=30),
    db: AsyncSession = Depends(get_db),
):
    """v5.3 replacement for the winrate-ceiling gate.

    For every strategy:
      1. Compute baseline metrics (winrate, roi, odds_coverage) via
         ``compute_strategy_metrics_with_real_odds``.
      2. Run walk-forward validation on the same picks.
      3. Pass BOTH into ``_compute_walk_forward_status`` which
         prefers the walk-forward signal when available.
      4. Set is_active only for strategies with status == "validated".

    Returns a ranked per-strategy summary plus the totals counter.
    """
    from app.models.prediction import PredictionEvaluation
    from app.services.roi_calculator import compute_strategy_metrics_with_real_odds

    result = await db.execute(select(Strategy).order_by(Strategy.name))
    strategies = list(result.scalars().all())

    # Pre-fetch every evaluated prediction + schedule once.
    pre_fetch_stmt = (
        select(Prediction, PredictionEvaluation, Match.scheduled_at)
        .join(Match, Match.id == Prediction.match_id)
        .join(PredictionEvaluation, PredictionEvaluation.prediction_id == Prediction.id)
        # v8.1 filter: restrict walk-forward to v8.1 predictions
        .where(trackrecord_filter())
        .order_by(Match.scheduled_at.asc())
    )
    pre_fetched = (await db.execute(pre_fetch_stmt)).all()

    # H2: hydrate odds once for the entire universe so every strategy in
    # this batch can match its odds-based rules.
    odds_map = await _load_odds_map(
        list({pred.match_id for pred, _, _ in pre_fetched}), db
    )

    # Picks-only tuples for the metrics call
    base_picks_by_strategy: dict = {}

    summary: list[dict] = []
    for strat in strategies:
        matched: list[tuple] = []
        for pred, evaluation, _sched in pre_fetched:
            if evaluate_strategy(
                strat, pred, odds=odds_map.get(pred.match_id)
            ):
                matched.append((pred, evaluation))
        sample_size = len(matched)

        if sample_size == 0:
            winrate = 0.0
            roi = 0.0
            odds_coverage_pct = 0.0
            avg_odds_used = 0.0
        else:
            metrics = await compute_strategy_metrics_with_real_odds(
                picks=matched,
                db=db,
            )
            winrate = metrics["winrate"]
            roi = metrics["roi"]
            odds_coverage_pct = metrics["odds_coverage_pct"]
            avg_odds_used = metrics["avg_odds_used"]

        # Walk-forward pass — reuse the pre-fetched rows.
        wf_result = await _walk_forward_for_strategy(
            strategy=strat,
            train_days=train_days,
            test_days=test_days,
            db=db,
            pre_fetched_rows=pre_fetched,
        )

        validation_status, notes = _compute_walk_forward_status(
            sample_size=sample_size,
            winrate=winrate,
            roi=roi,
            odds_coverage_pct=odds_coverage_pct,
            wf=wf_result,
        )

        was_active = bool(strat.is_active)
        should_be_active = validation_status == "validated"
        if was_active != should_be_active:
            strat.is_active = should_be_active

        summary.append(
            {
                "id": str(strat.id),
                "name": strat.name,
                "sample_size": sample_size,
                "raw_winrate": round(winrate, 4),
                "raw_roi": round(roi, 4),
                "odds_coverage_pct": odds_coverage_pct,
                "avg_odds_used": avg_odds_used,
                "walk_forward": {
                    "total_windows": wf_result.get("total_windows", 0),
                    "positive_windows": wf_result.get("positive_windows", 0),
                    "positive_windows_ratio": wf_result.get("positive_windows_ratio", 0.0),
                    "mean_test_roi": wf_result.get("mean_test_roi", 0.0),
                    "std_test_roi": wf_result.get("std_test_roi", 0.0),
                    "sharpe": wf_result.get("sharpe", 0.0),
                },
                "validation_status": validation_status,
                "validation_notes": notes,
                "was_active": was_active,
                "is_active": bool(strat.is_active),
                "flipped": was_active != should_be_active,
            }
        )

    await db.commit()

    # Bust caches
    from app.core.cache import cache_delete
    for row in summary:
        try:
            await cache_delete(f"strategy:metrics:{row['id']}")
            await cache_delete(f"strategy:today:{row['id']}")
        except Exception:
            pass

    # Rank by positive_windows_ratio desc, then Sharpe desc.
    summary.sort(
        key=lambda r: (
            r["walk_forward"]["positive_windows_ratio"],
            r["walk_forward"]["sharpe"],
            r["raw_roi"],
        ),
        reverse=True,
    )

    return {
        "total_strategies": len(summary),
        "validated": sum(1 for r in summary if r["validation_status"] == "validated"),
        "under_investigation": sum(
            1 for r in summary if r["validation_status"] == "under_investigation"
        ),
        "rejected": sum(1 for r in summary if r["validation_status"] == "rejected"),
        "break_even": sum(1 for r in summary if r["validation_status"] == "break_even"),
        "insufficient_data": sum(
            1 for r in summary if r["validation_status"] == "insufficient_data"
        ),
        "results": summary,
    }


@router.post(
    "/validation-refresh",
    summary="Recompute validation_status for every strategy and sync is_active",
)
async def refresh_strategy_validation(
    db: AsyncSession = Depends(get_db),
):
    """Walk every strategy, recompute its metrics, apply the plausibility gates
    in :func:`_compute_validation_status`, and set ``is_active`` to ``True``
    only for strategies whose status is ``validated``.

    Returns a per-strategy breakdown so it is safe to run this from curl / a
    Railway one-off without hitting the dashboard. Idempotent — safe to rerun.

    This is the manual knob Dennis uses after the next deploy to flush the
    5 leaky "Profitable" strategies off the live Strategy Lab. See
    ``docs/session_audit_report.md`` for context.
    """
    from app.models.prediction import PredictionEvaluation

    result = await db.execute(select(Strategy).order_by(Strategy.name))
    strategies = result.scalars().all()

    # Pre-fetch every evaluated prediction once — cheaper than N queries.
    pred_rows = (
        await db.execute(
            select(Prediction, PredictionEvaluation)
            .join(Match, Match.id == Prediction.match_id)
            .join(PredictionEvaluation, PredictionEvaluation.prediction_id == Prediction.id)
        )
    ).all()

    # v5: use the real-odds ROI helper for the refresh too, so
    # ``validation_status`` is decided on the same numbers the user sees
    # on the metrics endpoint.
    from app.services.roi_calculator import compute_strategy_metrics_with_real_odds

    # H2: bulk-load odds once so odds-based rules can match.
    odds_map = await _load_odds_map(
        list({pred.match_id for pred, _ in pred_rows}), db
    )

    summary: list[dict] = []
    for strat in strategies:
        matched: list[tuple] = []
        for pred, evaluation in pred_rows:
            if evaluate_strategy(
                strat, pred, odds=odds_map.get(pred.match_id)
            ):
                matched.append((pred, evaluation))
        sample_size = len(matched)
        if sample_size == 0:
            winrate = 0.0
            roi = 0.0
            odds_coverage_pct = 0.0
            avg_odds_used = 0.0
        else:
            metrics = await compute_strategy_metrics_with_real_odds(
                picks=matched,
                db=db,
            )
            winrate = metrics["winrate"]
            roi = metrics["roi"]
            odds_coverage_pct = metrics["odds_coverage_pct"]
            avg_odds_used = metrics["avg_odds_used"]

        validation_status, notes = _compute_validation_status(
            sample_size=sample_size, winrate=winrate, roi=roi
        )

        was_active = bool(strat.is_active)
        should_be_active = validation_status == "validated"
        if was_active != should_be_active:
            strat.is_active = should_be_active

        summary.append(
            {
                "id": str(strat.id),
                "name": strat.name,
                "sample_size": sample_size,
                "raw_winrate": round(winrate, 4),
                "raw_roi": round(roi, 4),
                "odds_coverage_pct": odds_coverage_pct,
                "avg_odds_used": avg_odds_used,
                "validation_status": validation_status,
                "validation_notes": notes,
                "was_active": was_active,
                "is_active": bool(strat.is_active),
                "flipped": was_active != should_be_active,
            }
        )

    await db.commit()

    # Bust the per-strategy metric cache so the next frontend poll reflects
    # the new status immediately.
    from app.core.cache import cache_delete
    for row in summary:
        try:
            await cache_delete(f"strategy:metrics:{row['id']}")
            await cache_delete(f"strategy:today:{row['id']}")
        except Exception:
            pass

    return {
        "total_strategies": len(summary),
        "validated": sum(1 for r in summary if r["validation_status"] == "validated"),
        "under_investigation": sum(
            1 for r in summary if r["validation_status"] == "under_investigation"
        ),
        "rejected": sum(1 for r in summary if r["validation_status"] == "rejected"),
        "break_even": sum(1 for r in summary if r["validation_status"] == "break_even"),
        "insufficient_data": sum(
            1 for r in summary if r["validation_status"] == "insufficient_data"
        ),
        "results": summary,
    }
