"""Strategy API routes."""
from __future__ import annotations

import uuid
from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import aliased

from app.db.session import get_db
from app.models.league import League
from app.models.match import Match
from app.models.prediction import Prediction
from app.models.strategy import Strategy
from app.models.team import Team
from app.schemas.strategy import (
    StrategyPickPrediction,
    StrategyPicksResponse,
    StrategyResponse,
)
from app.services.strategy_engine import evaluate_strategy

router = APIRouter()


# ──────────────────────────────────────────────────────────────────────────────
# Validation status — conservative plausibility gates
# ──────────────────────────────────────────────────────────────────────────────
#
# The numbers reported by this endpoint are computed on predictions generated by
# the current ensemble forecast model. As of 2026-04-11, that model has a known
# feature-leakage issue: the EloModel is instantiated fresh per prediction and
# seeds its ratings from ``app/forecasting/team_seeds.py``, a hand-curated table
# of "current-day" Elo values. When the sync job or ``admin_backfill`` generates
# predictions for historical fixtures, the seeds are still the same static
# present-day numbers — so the model is effectively using post-hoc knowledge of
# which teams turned out to be strong. That inflates strike rates far above what
# any real 1X2 model can achieve.
#
# A well-calibrated 1X2 model on European top-five + Eredivisie caps out around
# 53-56% strike rate and 1-5% ROI after commission. Anything materially above
# those numbers on samples of a few hundred picks is virtually certain to be a
# data-quality artefact, not an edge. We therefore gate strategies with the
# following honest criteria, which take effect on every ``/metrics`` call and
# every ``/validation-refresh`` run:
#
#   * sample_size < 30                 → "insufficient_data"
#   * winrate > 0.58                   → "under_investigation"
#       (implausibly high without leakage, regardless of ROI)
#   * roi > 0.08                       → "under_investigation"
#       (implausibly high ROI for a flat-odds 1X2 strategy)
#   * roi < -0.02                      → "rejected"
#   * otherwise, roi > 0.02            → "validated"
#   * otherwise                        → "break_even"
#
# These are deliberately blunt. They are a tripwire, not a substitute for a
# proper walk-forward / bootstrap validation pipeline — but they will prevent
# the frontend from confidently displaying impossible ROIs while the underlying
# Elo leakage is being fixed.

_LEAKAGE_WINRATE_CEILING = 0.58
_LEAKAGE_ROI_CEILING = 0.08


def _compute_validation_status(
    sample_size: int, winrate: float, roi: float
) -> tuple[str, str]:
    """Return (status, notes) for a given set of computed metrics.

    Notes explain *why* the status was assigned, so the frontend can surface a
    tooltip or badge. See module docstring above for the exact criteria.
    """
    if sample_size < 30:
        return (
            "insufficient_data",
            f"Only {sample_size} picks — need ≥30 before we trust any number.",
        )
    if winrate > _LEAKAGE_WINRATE_CEILING:
        return (
            "under_investigation",
            (
                f"Strike rate of {winrate:.1%} exceeds the {_LEAKAGE_WINRATE_CEILING:.0%} "
                "plausibility ceiling for 1X2. Likely feature leakage from the "
                "static team_seeds.py Elo table — metrics pending rebuild with "
                "point-in-time ratings."
            ),
        )
    if roi > _LEAKAGE_ROI_CEILING:
        return (
            "under_investigation",
            (
                f"ROI of {roi:+.1%} exceeds the {_LEAKAGE_ROI_CEILING:+.0%} plausibility "
                "ceiling for 1X2 at flat 1.90 odds. Treat as a data artefact until "
                "validated with real historical odds and point-in-time features."
            ),
        )
    if roi < -0.02:
        return (
            "rejected",
            f"ROI of {roi:+.1%} is materially negative — strategy does not beat the vig.",
        )
    if roi > 0.02:
        return (
            "validated",
            f"ROI {roi:+.1%} on {sample_size} picks is within the plausible range for a real edge.",
        )
    return (
        "break_even",
        f"ROI {roi:+.1%} is within the break-even band; no reliable signal yet.",
    )


@router.get(
    "/",
    response_model=List[StrategyResponse],
    summary="List all strategies",
)
async def list_strategies(
    active_only: bool = Query(default=False, description="Return only active strategies"),
    db: AsyncSession = Depends(get_db),
) -> List[StrategyResponse]:
    """Return all strategies ordered by creation date."""
    q = select(Strategy).order_by(Strategy.created_at.desc())
    if active_only:
        q = q.where(Strategy.is_active.is_(True))

    result = await db.execute(q)
    strategies = result.scalars().all()
    return [StrategyResponse.model_validate(s) for s in strategies]


@router.get(
    "/{strategy_id}",
    response_model=StrategyResponse,
    summary="Get a single strategy",
)
async def get_strategy(
    strategy_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
) -> StrategyResponse:
    """Return a single strategy by ID."""
    result = await db.execute(
        select(Strategy).where(Strategy.id == strategy_id)
    )
    strategy = result.scalar_one_or_none()
    if strategy is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Strategy {strategy_id} not found.",
        )
    return StrategyResponse.model_validate(strategy)


@router.get(
    "/{strategy_id}/picks",
    response_model=StrategyPicksResponse,
    summary="Get predictions matching a strategy",
)
async def get_strategy_picks(
    strategy_id: uuid.UUID,
    limit: int = Query(default=50, ge=1, le=200, description="Max picks to return"),
    offset: int = Query(default=0, ge=0, description="Pagination offset"),
    db: AsyncSession = Depends(get_db),
) -> StrategyPicksResponse:
    """
    Evaluate all recent predictions against the strategy and return matching picks.

    Predictions are evaluated in-memory against the strategy rules. Odds-based
    rules are skipped when odds data is not available.
    """
    # Fetch the strategy
    strat_result = await db.execute(
        select(Strategy).where(Strategy.id == strategy_id)
    )
    strategy = strat_result.scalar_one_or_none()
    if strategy is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Strategy {strategy_id} not found.",
        )

    # Fetch predictions with match context + evaluation
    from app.models.prediction import PredictionEvaluation
    from app.models.match import MatchResult, MatchStatus as MS

    HomeTeam = aliased(Team)
    AwayTeam = aliased(Team)

    q = (
        select(
            Prediction,
            Match.scheduled_at,
            Match.status.label("match_status"),
            HomeTeam.name.label("home_team_name"),
            AwayTeam.name.label("away_team_name"),
            League.name.label("league_name"),
            PredictionEvaluation.actual_outcome,
            PredictionEvaluation.is_correct,
            MatchResult.home_score,
            MatchResult.away_score,
        )
        .join(Match, Match.id == Prediction.match_id)
        .join(HomeTeam, HomeTeam.id == Match.home_team_id)
        .join(AwayTeam, AwayTeam.id == Match.away_team_id)
        .join(League, League.id == Match.league_id)
        .outerjoin(PredictionEvaluation, PredictionEvaluation.prediction_id == Prediction.id)
        .outerjoin(MatchResult, MatchResult.match_id == Match.id)
        .order_by(Match.scheduled_at.desc())
    )

    result = await db.execute(q)
    rows = result.all()

    # Evaluate each prediction against strategy rules
    matched_picks: list[StrategyPickPrediction] = []
    for row in rows:
        prediction = row[0]
        scheduled_at = row[1]
        match_status = row[2]
        home_team_name = row[3]
        away_team_name = row[4]
        league_name = row[5]
        actual_outcome = row[6]
        is_correct = row[7]
        home_score = row[8]
        away_score = row[9]

        odds = None
        if evaluate_strategy(strategy, prediction, odds):
            # Determine pick
            probs = {"HOME": prediction.home_win_prob, "DRAW": prediction.draw_prob or 0, "AWAY": prediction.away_win_prob}
            pick = max(probs, key=lambda k: probs[k])

            # Calculate P/L (flat 1u stake, assume avg odds ~1.9)
            pnl = None
            if is_correct is not None:
                pnl = 0.9 if is_correct else -1.0

            status_str = match_status.value if hasattr(match_status, "value") else str(match_status)

            matched_picks.append(
                StrategyPickPrediction(
                    id=prediction.id,
                    match_id=prediction.match_id,
                    predicted_at=prediction.predicted_at,
                    home_win_prob=prediction.home_win_prob,
                    draw_prob=prediction.draw_prob,
                    away_win_prob=prediction.away_win_prob,
                    confidence=prediction.confidence,
                    prediction_type=prediction.prediction_type,
                    pick=pick,
                    home_team_name=home_team_name,
                    away_team_name=away_team_name,
                    scheduled_at=scheduled_at,
                    league_name=league_name,
                    match_status=status_str,
                    actual_outcome=actual_outcome,
                    is_correct=is_correct,
                    home_score=home_score,
                    away_score=away_score,
                    pnl=pnl,
                )
            )

    total = len(matched_picks)
    paginated = matched_picks[offset : offset + limit]

    return StrategyPicksResponse(
        strategy=StrategyResponse.model_validate(strategy),
        total=total,
        picks=paginated,
    )


@router.get(
    "/{strategy_id}/today-picks",
    summary="Get upcoming matches that match this strategy",
)
async def get_strategy_today_picks(
    strategy_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
):
    """Return upcoming scheduled matches that pass this strategy's filters."""
    from app.core.cache import cache_get, cache_set
    from datetime import datetime, timedelta, timezone
    from app.models.match import MatchStatus

    # Check cache
    cache_key = f"strategy:today:{strategy_id}"
    cached = await cache_get(cache_key)
    if cached is not None:
        return cached

    # Get strategy
    strat_result = await db.execute(select(Strategy).where(Strategy.id == strategy_id))
    strategy = strat_result.scalar_one_or_none()
    if strategy is None:
        raise HTTPException(status_code=404, detail="Strategy not found")

    # Get upcoming predictions
    now = datetime.now(timezone.utc)
    cutoff = now + timedelta(hours=72)

    HomeTeam = aliased(Team)
    AwayTeam = aliased(Team)

    q = (
        select(
            Prediction,
            Match.scheduled_at,
            HomeTeam.name.label("home"),
            AwayTeam.name.label("away"),
            League.name.label("league"),
        )
        .join(Match, Match.id == Prediction.match_id)
        .join(HomeTeam, HomeTeam.id == Match.home_team_id)
        .join(AwayTeam, AwayTeam.id == Match.away_team_id)
        .join(League, League.id == Match.league_id)
        .where(
            Match.status == MatchStatus.SCHEDULED,
            Match.scheduled_at >= now,
            Match.scheduled_at <= cutoff,
        )
        .order_by(Match.scheduled_at)
    )
    rows = (await db.execute(q)).all()

    picks = []
    for pred, scheduled_at, home, away, league in rows:
        if evaluate_strategy(strategy, pred, odds=None):
            probs = {
                "HOME": pred.home_win_prob,
                "DRAW": pred.draw_prob or 0,
                "AWAY": pred.away_win_prob,
            }
            pick = max(probs, key=lambda k: probs[k])
            picks.append(
                {
                    "match_id": str(pred.match_id),
                    "home_team": home,
                    "away_team": away,
                    "league": league,
                    "kickoff": scheduled_at.isoformat(),
                    "pick": pick,
                    "home_win_prob": round(pred.home_win_prob, 4),
                    "draw_prob": round(pred.draw_prob or 0, 4),
                    "away_win_prob": round(pred.away_win_prob, 4),
                    "confidence": round(pred.confidence, 4),
                }
            )

    result = {
        "strategy_name": strategy.name,
        "picks_count": len(picks),
        "picks": picks,
    }
    await cache_set(cache_key, result, ttl=600)  # 10 min cache
    return result


@router.get(
    "/{strategy_id}/metrics",
    summary="Get performance metrics for a strategy",
)
async def get_strategy_metrics(
    strategy_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
):
    """
    Calculate performance metrics for a strategy based on evaluated predictions.
    Results are cached in Redis for 15 minutes.
    Returns: sample_size, winrate, roi, max_drawdown, profit_factor.
    """
    from app.core.cache import cache_get, cache_set
    from app.models.prediction import PredictionEvaluation

    # Check cache first
    cache_key = f"strategy:metrics:{strategy_id}"
    cached = await cache_get(cache_key)
    if cached is not None:
        return cached

    # Fetch strategy
    strat_result = await db.execute(select(Strategy).where(Strategy.id == strategy_id))
    strategy = strat_result.scalar_one_or_none()
    if strategy is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Strategy not found")

    # Get all evaluated predictions
    HomeTeam = aliased(Team)
    AwayTeam = aliased(Team)

    q = (
        select(Prediction, PredictionEvaluation)
        .join(Match, Match.id == Prediction.match_id)
        .join(PredictionEvaluation, PredictionEvaluation.prediction_id == Prediction.id)
        .join(HomeTeam, HomeTeam.id == Match.home_team_id)
        .join(AwayTeam, AwayTeam.id == Match.away_team_id)
        .join(League, League.id == Match.league_id)
        .order_by(Match.scheduled_at)
    )
    rows = (await db.execute(q)).all()

    # Filter for strategy matches
    matched_and_evaluated = []
    for pred, evaluation in rows:
        if evaluate_strategy(strategy, pred, odds=None):
            matched_and_evaluated.append((pred, evaluation))

    sample_size = len(matched_and_evaluated)
    if sample_size == 0:
        return {
            "strategy_id": str(strategy_id),
            "strategy_name": strategy.name,
            "sample_size": 0,
            "winrate": 0.0,
            "roi": 0.0,
            "max_drawdown": 0.0,
            "profit_factor": 0.0,
            "avg_brier": 0.0,
            "odds_coverage_pct": 0.0,
            "avg_odds_used": 0.0,
            "has_data": False,
            "validation_status": "insufficient_data",
            "validation_notes": "No evaluated predictions yet for this strategy.",
        }

    # v5: use real historical odds from odds_history when available.
    # Falls back to 1.90 flat for picks with no odds row.
    from app.services.roi_calculator import compute_strategy_metrics_with_real_odds
    metrics = await compute_strategy_metrics_with_real_odds(
        picks=matched_and_evaluated,
        db=db,
    )
    winrate = metrics["winrate"]
    roi = metrics["roi"]
    correct = metrics["wins"]
    losses = metrics["losses"]

    avg_brier = sum(
        (ev.brier_score or 0.0) for _, ev in matched_and_evaluated
    ) / sample_size

    validation_status, validation_notes = _compute_validation_status(
        sample_size=sample_size, winrate=winrate, roi=roi
    )

    # For strategies flagged as under_investigation we deliberately clamp the
    # displayed numbers so downstream clients (e.g. the current frontend
    # which renders a "Profitable" badge from ``roi > 0``) don't show glowing
    # metrics while the underlying feature leakage is still being fixed. The
    # *raw* computed numbers are preserved under ``raw_winrate`` / ``raw_roi``
    # so the upcoming strategy-lab rebuild can still show them behind a
    # "disputed" treatment.
    raw_winrate = round(winrate, 4)
    raw_roi = round(roi, 4)
    if validation_status == "under_investigation":
        display_winrate = 0.0
        display_roi = 0.0
    else:
        display_winrate = raw_winrate
        display_roi = raw_roi

    result = {
        "strategy_id": str(strategy_id),
        "strategy_name": strategy.name,
        "sample_size": sample_size,
        # ``winrate`` / ``roi`` carry the DISPLAY values (zeroed for suspicious
        # strategies). Existing frontend code reading these fields will stop
        # labelling them as profitable.
        "winrate": display_winrate,
        "roi": display_roi,
        "raw_winrate": raw_winrate,
        "raw_roi": raw_roi,
        "max_drawdown": metrics["max_drawdown"],
        "profit_factor": metrics["profit_factor"],
        "avg_brier": round(avg_brier, 6),
        "correct": correct,
        "incorrect": losses,
        "has_data": True,
        # v5 additions — see API_CONTRACT.md for semantics.
        "validation_status": validation_status,
        "validation_notes": validation_notes,
        "odds_coverage_pct": metrics["odds_coverage_pct"],
        "avg_odds_used": metrics["avg_odds_used"],
    }

    # Cache for 15 minutes
    await cache_set(cache_key, result, ttl=900)
    return result


@router.post(
    "/validation-refresh",
    summary="Recompute validation_status for every strategy and sync is_active",
)
async def refresh_strategy_validation(
    db: AsyncSession = Depends(get_db),
):
    """Walk every strategy, recompute its metrics, apply the plausibility gates
    in :func:`_compute_validation_status`, and set ``is_active`` to ``True``
    only for strategies whose status is ``validated``.

    Returns a per-strategy breakdown so it is safe to run this from curl / a
    Railway one-off without hitting the dashboard. Idempotent — safe to rerun.

    This is the manual knob Dennis uses after the next deploy to flush the
    5 leaky "Profitable" strategies off the live Strategy Lab. See
    ``docs/session_audit_report.md`` for context.
    """
    from app.models.prediction import PredictionEvaluation

    result = await db.execute(select(Strategy).order_by(Strategy.name))
    strategies = result.scalars().all()

    # Pre-fetch every evaluated prediction once — cheaper than N queries.
    pred_rows = (
        await db.execute(
            select(Prediction, PredictionEvaluation)
            .join(Match, Match.id == Prediction.match_id)
            .join(PredictionEvaluation, PredictionEvaluation.prediction_id == Prediction.id)
        )
    ).all()

    # v5: use the real-odds ROI helper for the refresh too, so
    # ``validation_status`` is decided on the same numbers the user sees
    # on the metrics endpoint.
    from app.services.roi_calculator import compute_strategy_metrics_with_real_odds

    summary: list[dict] = []
    for strat in strategies:
        matched: list[tuple] = []
        for pred, evaluation in pred_rows:
            if evaluate_strategy(strat, pred, odds=None):
                matched.append((pred, evaluation))
        sample_size = len(matched)
        if sample_size == 0:
            winrate = 0.0
            roi = 0.0
            odds_coverage_pct = 0.0
            avg_odds_used = 0.0
        else:
            metrics = await compute_strategy_metrics_with_real_odds(
                picks=matched,
                db=db,
            )
            winrate = metrics["winrate"]
            roi = metrics["roi"]
            odds_coverage_pct = metrics["odds_coverage_pct"]
            avg_odds_used = metrics["avg_odds_used"]

        validation_status, notes = _compute_validation_status(
            sample_size=sample_size, winrate=winrate, roi=roi
        )

        was_active = bool(strat.is_active)
        should_be_active = validation_status == "validated"
        if was_active != should_be_active:
            strat.is_active = should_be_active

        summary.append(
            {
                "id": str(strat.id),
                "name": strat.name,
                "sample_size": sample_size,
                "raw_winrate": round(winrate, 4),
                "raw_roi": round(roi, 4),
                "odds_coverage_pct": odds_coverage_pct,
                "avg_odds_used": avg_odds_used,
                "validation_status": validation_status,
                "validation_notes": notes,
                "was_active": was_active,
                "is_active": bool(strat.is_active),
                "flipped": was_active != should_be_active,
            }
        )

    await db.commit()

    # Bust the per-strategy metric cache so the next frontend poll reflects
    # the new status immediately.
    from app.core.cache import cache_delete
    for row in summary:
        try:
            await cache_delete(f"strategy:metrics:{row['id']}")
            await cache_delete(f"strategy:today:{row['id']}")
        except Exception:
            pass

    return {
        "total_strategies": len(summary),
        "validated": sum(1 for r in summary if r["validation_status"] == "validated"),
        "under_investigation": sum(
            1 for r in summary if r["validation_status"] == "under_investigation"
        ),
        "rejected": sum(1 for r in summary if r["validation_status"] == "rejected"),
        "break_even": sum(1 for r in summary if r["validation_status"] == "break_even"),
        "insufficient_data": sum(
            1 for r in summary if r["validation_status"] == "insufficient_data"
        ),
        "results": summary,
    }
