"""Per-user single-use Telegram invite link tracking.

The paid-tier Telegram channels (Silver/Gold/Platinum) are private. Each
subscriber gets their **own** invite link generated by the bot via
``createChatInviteLink`` with ``member_limit=1``. After one person has
used it, Telegram invalidates the link automatically — so a leaked link
won't let a second freeloader join.

This table is the audit trail mapping user → tier → link, plus the
``used_at`` timestamp we update when the link is consumed (best-effort,
via the ``my_chat_member`` Telegram update; absence of that update
doesn't break anything because Telegram itself enforces the 1-use limit
server-side).

Why a per-(user, tier) row instead of one row per user:
    - A user can in theory upgrade Silver → Gold and keep both links.
    - Tier rows let us cleanly invalidate / regenerate one tier's link
      without touching the others.

Idempotency rule: ``get_or_create_invite(user, tier)`` returns the
existing unused row if there is one. We only generate a new link when
the previous one was used or has expired. Stripe webhooks pre-warming
the link can be called repeatedly without spamming the Bot API.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional
import uuid

from sqlalchemy import (
    DateTime,
    ForeignKey,
    Index,
    SmallInteger,
    String,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.session import Base
from app.models.base import TimestampMixin, UUIDPrimaryKey


class TelegramInvite(Base, UUIDPrimaryKey, TimestampMixin):
    __tablename__ = "telegram_invites"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # PickTier integer (0 free / 1 silver / 2 gold / 3 platinum). Stored
    # as a small int rather than the SAEnum so the column survives if we
    # ever rename a tier slug — the int is the canonical identity.
    tier: Mapped[int] = mapped_column(SmallInteger, nullable=False)

    # The numeric Telegram chat id (negative for channels) the link
    # belongs to. Stored alongside the link so a future channel rotation
    # is auditable — old rows still resolve to the channel that issued
    # them.
    chat_id: Mapped[str] = mapped_column(String(64), nullable=False)

    # Full https://t.me/+<token> link as Telegram returned it. Long-form
    # because Telegram tokens are ~22 chars + URL prefix; 256 is plenty.
    invite_link: Mapped[str] = mapped_column(String(256), nullable=False)

    # Optional expiry mirrored from the Bot API call (we currently leave
    # links open-ended so a slow-clicking user doesn't get locked out;
    # the ``member_limit=1`` already enforces single-use).
    expire_date: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # When the user actually joined via this link. NULL = link still
    # spendable. Updated by the ``my_chat_member`` webhook handler when
    # a new member appears in the channel — best-effort; the link is
    # already single-use server-side, so a missed webhook just leaves
    # the row stale but doesn't admit a second person.
    used_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    user = relationship("User", lazy="joined")

    __table_args__ = (
        # One active link per (user, tier). Older rows for the same
        # pair survive only when superseded — see the service layer
        # which marks old rows as ``used_at=now()`` before issuing a
        # replacement so the unique constraint stays satisfied via the
        # partial index below.
        UniqueConstraint("user_id", "tier", name="uq_tginvite_user_tier"),
        Index("ix_tginvite_used_at", "used_at"),
    )
