"""Per-user single-use Telegram invite link issuance.

For paid-tier (Silver/Gold/Platinum) channels we keep them PRIVATE in
Telegram and hand subscribers a personal invite link generated by the
bot via ``createChatInviteLink`` with ``member_limit=1``. After one
person has used it, Telegram invalidates the link server-side — so
even if a subscriber leaks their link to a friend, only ONE additional
person can join (whoever clicks first), and any further clicks fail.

Service contract::

    invite = await get_or_create_invite(db, user, tier)
    # invite.invite_link  →  https://t.me/+<unique>

Idempotency:
    - Repeated calls for the same (user, tier) return the existing row
      while ``used_at IS NULL``. That makes the Stripe-webhook
      pre-warm safe to retry, and lets the user's dashboard / thank-
      you page render the same link across page loads.
    - When ``used_at`` is set (the user joined), a new call regenerates
      a fresh link — handy if the user kicked themselves and wants
      back in. The previous row is hard-deleted so the unique
      ``(user_id, tier)`` constraint stays satisfied.

Authorisation:
    The CALLER is responsible for confirming the user actually has the
    requested tier. The endpoint layer (``/api/telegram/my-invite``)
    uses ``get_current_tier`` for that — the service trusts whoever
    invoked it.

Channel-not-configured handling:
    When ``TELEGRAM_CHANNEL_<TIER>`` env var isn't set, the function
    returns ``None`` instead of raising. The endpoint maps that to a
    ``409 Conflict`` so the frontend can show "channel not ready yet,
    please come back later" rather than a 500.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.tier_system import PickTier
from app.models.telegram_invite import TelegramInvite
from app.models.user import User
from app.services.telegram_posting import _channel_for_tier
from app.services.telegram_service import (
    TelegramError,
    create_chat_invite_link,
)

logger = logging.getLogger(__name__)


def _invite_name(user: User, tier: PickTier) -> str:
    """Build a label that the operator sees in Telegram's invite-link UI.

    Format: ``<tier>-<short-uuid>`` so a quick glance in
    Telegram → Manage Channel → Invite Links tells you which subscriber
    a link belongs to. The uuid prefix is enough to disambiguate across
    a few thousand subscribers without leaking the full id.
    """
    short = str(user.id)[:8]
    return f"{tier.name.lower()}-{short}"


async def get_or_create_invite(
    db: AsyncSession,
    user: User,
    tier: PickTier,
) -> Optional[TelegramInvite]:
    """Return a single-use Telegram invite for ``user`` on ``tier``.

    See module docstring for the full contract. Returns ``None`` only
    when the tier's channel env var isn't configured yet — every other
    failure path (Bot API down, network error) raises ``TelegramError``
    so the caller can surface a clear error.
    """
    if tier == PickTier.FREE:
        # Free is a public channel; no per-user invite needed.
        return None

    chat_id = _channel_for_tier(tier)
    if not chat_id:
        logger.info(
            "telegram_invites: tier=%s channel not configured",
            tier.name,
        )
        return None

    # Reuse the existing unspent row if present. This is the hot path —
    # most calls (user revisiting their dashboard, Stripe webhook re-
    # firing) hit this branch.
    existing_stmt = select(TelegramInvite).where(
        TelegramInvite.user_id == user.id,
        TelegramInvite.tier == int(tier),
    )
    existing = (await db.execute(existing_stmt)).scalar_one_or_none()

    if existing is not None and existing.used_at is None:
        return existing

    # Either no row yet, OR a row exists but was already consumed. In the
    # consumed case we delete the stale row first so the unique
    # constraint won't reject the fresh insert. We do NOT just update in
    # place — the audit trail is more useful when an old "used_at"
    # value disappears with the row, so a future support query "did
    # this user ever join Silver?" returns a clean yes/no.
    if existing is not None:
        await db.delete(existing)
        await db.flush()

    name = _invite_name(user, tier)
    try:
        bot_response = await create_chat_invite_link(
            chat_id=chat_id,
            name=name,
            member_limit=1,
        )
    except TelegramError:
        # Bubble up — the endpoint layer turns this into a 502 with the
        # original error message so the operator sees it on the
        # admin / Sentry side.
        raise

    invite_link = bot_response.get("invite_link")
    if not invite_link:
        raise TelegramError(
            f"Bot API returned no invite_link in response: {bot_response}"
        )

    expire_ts = bot_response.get("expire_date")
    expire_dt: Optional[datetime] = None
    if expire_ts:
        expire_dt = datetime.fromtimestamp(int(expire_ts), tz=timezone.utc)

    invite = TelegramInvite(
        user_id=user.id,
        tier=int(tier),
        chat_id=str(chat_id),
        invite_link=invite_link,
        expire_date=expire_dt,
        used_at=None,
    )
    db.add(invite)
    await db.commit()
    await db.refresh(invite)
    return invite


async def mark_invite_used(
    db: AsyncSession,
    chat_id: str,
    invite_link: str,
) -> bool:
    """Mark an invite row as consumed.

    Called by the ``my_chat_member`` webhook handler when a new member
    appears in a paid-tier channel via a tracked invite link. Returns
    True when a row was updated, False when no matching row exists
    (e.g. the operator handed out a manual link from outside the
    pre-generated set — Telegram still enforced single-use, we just
    don't have an audit row).
    """
    stmt = select(TelegramInvite).where(
        TelegramInvite.chat_id == str(chat_id),
        TelegramInvite.invite_link == invite_link,
        TelegramInvite.used_at.is_(None),
    )
    row = (await db.execute(stmt)).scalar_one_or_none()
    if row is None:
        return False
    row.used_at = datetime.now(timezone.utc)
    await db.commit()
    return True


__all__ = [
    "get_or_create_invite",
    "mark_invite_used",
]
