"""initial schema

Revision ID: 239b393c2b2b
Revises: 
Create Date: 2026-04-06 10:25:59.133407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '239b393c2b2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('adapter_type', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('feature_snapshots',
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('feature_set', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_snapshots_prediction_id'), 'feature_snapshots', ['prediction_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('sport_scope', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('training_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sports',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_sports_is_active', 'sports', ['is_active'], unique=False)
    op.create_index('ix_sports_name', 'sports', ['name'], unique=False)
    op.create_index('ix_sports_slug', 'sports', ['slug'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_type', 'audit_logs', ['entity_type'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sport_slug', sa.String(length=50), nullable=False),
    sa.Column('league_slug', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_predictions', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('log_loss', sa.Float(), nullable=True),
    sa.Column('calibration_error', sa.Float(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtest_runs_model_version', 'backtest_runs', ['model_version_id'], unique=False)
    op.create_index('ix_backtest_runs_status', 'backtest_runs', ['status'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_runs_source', 'ingestion_runs', ['data_source_id'], unique=False)
    op.create_index('ix_ingestion_runs_started', 'ingestion_runs', ['started_at'], unique=False)
    op.create_index('ix_ingestion_runs_status', 'ingestion_runs', ['status'], unique=False)
    op.create_table('leagues',
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_leagues_country', 'leagues', ['country'], unique=False)
    op.create_index('ix_leagues_is_active', 'leagues', ['is_active'], unique=False)
    op.create_index('ix_leagues_slug', 'leagues', ['slug'], unique=False)
    op.create_index('ix_leagues_sport_id', 'leagues', ['sport_id'], unique=False)
    op.create_table('report_jobs',
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_jobs_status', 'report_jobs', ['status'], unique=False)
    op.create_index('ix_report_jobs_type', 'report_jobs', ['report_type'], unique=False)
    op.create_table('generated_reports',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['report_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generated_reports_job_id', 'generated_reports', ['job_id'], unique=False)
    op.create_table('ingestion_errors',
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_errors_run_id', 'ingestion_errors', ['ingestion_run_id'], unique=False)
    op.create_table('seasons',
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_seasons_end_date', 'seasons', ['end_date'], unique=False)
    op.create_index('ix_seasons_is_current', 'seasons', ['is_current'], unique=False)
    op.create_index('ix_seasons_league_id', 'seasons', ['league_id'], unique=False)
    op.create_index('ix_seasons_start_date', 'seasons', ['start_date'], unique=False)
    op.create_table('teams',
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('venue', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_teams_league_id', 'teams', ['league_id'], unique=False)
    op.create_index('ix_teams_name', 'teams', ['name'], unique=False)
    op.create_index('ix_teams_slug', 'teams', ['slug'], unique=False)
    op.create_table('matches',
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=True),
    sa.Column('home_team_id', sa.UUID(), nullable=False),
    sa.Column('away_team_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'FINISHED', 'POSTPONED', 'CANCELLED', name='matchstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(length=300), nullable=True),
    sa.Column('round_name', sa.String(length=100), nullable=True),
    sa.Column('matchday', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_matches_away_team_id', 'matches', ['away_team_id'], unique=False)
    op.create_index('ix_matches_external_id', 'matches', ['external_id'], unique=False)
    op.create_index('ix_matches_home_team_id', 'matches', ['home_team_id'], unique=False)
    op.create_index('ix_matches_league_id', 'matches', ['league_id'], unique=False)
    op.create_index('ix_matches_scheduled_at', 'matches', ['scheduled_at'], unique=False)
    op.create_index('ix_matches_status', 'matches', ['status'], unique=False)
    op.create_table('players',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_players_name', 'players', ['name'], unique=False)
    op.create_index('ix_players_slug', 'players', ['slug'], unique=False)
    op.create_index('ix_players_team_id', 'players', ['team_id'], unique=False)
    op.create_table('standings_snapshots',
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('drawn', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('goal_difference', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_standings_league_season', 'standings_snapshots', ['league_id', 'season_id'], unique=False)
    op.create_index('ix_standings_snapshot_date', 'standings_snapshots', ['snapshot_date'], unique=False)
    op.create_index('ix_standings_team_id', 'standings_snapshots', ['team_id'], unique=False)
    op.create_table('team_stats',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('goals_scored', sa.Integer(), nullable=False),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.Column('home_wins', sa.Integer(), nullable=False),
    sa.Column('away_wins', sa.Integer(), nullable=False),
    sa.Column('avg_goals_scored', sa.Float(), nullable=True),
    sa.Column('avg_goals_conceded', sa.Float(), nullable=True),
    sa.Column('extra_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_team_stats_team_season', 'team_stats', ['team_id', 'season_id'], unique=False)
    op.create_table('backtest_results',
    sa.Column('backtest_run_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('predicted_outcome', sa.String(length=50), nullable=False),
    sa.Column('actual_outcome', sa.String(length=50), nullable=False),
    sa.Column('home_win_prob', sa.Float(), nullable=False),
    sa.Column('draw_prob', sa.Float(), nullable=True),
    sa.Column('away_win_prob', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('brier_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtest_results_run_id', 'backtest_results', ['backtest_run_id'], unique=False)
    op.create_table('injuries',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('injury_type', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expected_return', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_injuries_player_id', 'injuries', ['player_id'], unique=False)
    op.create_index('ix_injuries_status', 'injuries', ['status'], unique=False)
    op.create_index('ix_injuries_team_id', 'injuries', ['team_id'], unique=False)
    op.create_table('match_results',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('home_score_ht', sa.Integer(), nullable=True),
    sa.Column('away_score_ht', sa.Integer(), nullable=True),
    sa.Column('winner', sa.String(length=10), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_index('ix_match_results_match_id', 'match_results', ['match_id'], unique=False)
    op.create_table('odds_history',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=False),
    sa.Column('home_odds', sa.Float(), nullable=False),
    sa.Column('draw_odds', sa.Float(), nullable=True),
    sa.Column('away_odds', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_odds_match_id', 'odds_history', ['match_id'], unique=False)
    op.create_index('ix_odds_recorded_at', 'odds_history', ['recorded_at'], unique=False)
    op.create_table('player_stats',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('appearances', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('stat_type', sa.String(length=50), nullable=True),
    sa.Column('extra_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_player_stats_player_season', 'player_stats', ['player_id', 'season_id'], unique=False)
    op.create_table('predictions',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prediction_type', sa.String(length=50), nullable=False),
    sa.Column('home_win_prob', sa.Float(), nullable=False),
    sa.Column('draw_prob', sa.Float(), nullable=True),
    sa.Column('away_win_prob', sa.Float(), nullable=False),
    sa.Column('predicted_home_score', sa.Float(), nullable=True),
    sa.Column('predicted_away_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_interval_low', sa.Float(), nullable=True),
    sa.Column('confidence_interval_high', sa.Float(), nullable=True),
    sa.Column('features_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_simulation', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_match_id', 'predictions', ['match_id'], unique=False)
    op.create_index('ix_predictions_model_version_id', 'predictions', ['model_version_id'], unique=False)
    op.create_index('ix_predictions_predicted_at', 'predictions', ['predicted_at'], unique=False)
    op.create_index('ix_predictions_type', 'predictions', ['prediction_type'], unique=False)
    op.create_table('prediction_evaluations',
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('actual_outcome', sa.String(length=50), nullable=False),
    sa.Column('actual_home_score', sa.Integer(), nullable=True),
    sa.Column('actual_away_score', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('brier_score', sa.Float(), nullable=False),
    sa.Column('log_loss', sa.Float(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    op.create_index('ix_pred_eval_evaluated_at', 'prediction_evaluations', ['evaluated_at'], unique=False)
    op.create_index('ix_pred_eval_prediction_id', 'prediction_evaluations', ['prediction_id'], unique=False)
    op.create_table('prediction_explanations',
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('top_factors_for', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('top_factors_against', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('similar_historical', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feature_importances', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_explanations')
    op.drop_index('ix_pred_eval_prediction_id', table_name='prediction_evaluations')
    op.drop_index('ix_pred_eval_evaluated_at', table_name='prediction_evaluations')
    op.drop_table('prediction_evaluations')
    op.drop_index('ix_predictions_type', table_name='predictions')
    op.drop_index('ix_predictions_predicted_at', table_name='predictions')
    op.drop_index('ix_predictions_model_version_id', table_name='predictions')
    op.drop_index('ix_predictions_match_id', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_player_stats_player_season', table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_index('ix_odds_recorded_at', table_name='odds_history')
    op.drop_index('ix_odds_match_id', table_name='odds_history')
    op.drop_table('odds_history')
    op.drop_index('ix_match_results_match_id', table_name='match_results')
    op.drop_table('match_results')
    op.drop_index('ix_injuries_team_id', table_name='injuries')
    op.drop_index('ix_injuries_status', table_name='injuries')
    op.drop_index('ix_injuries_player_id', table_name='injuries')
    op.drop_table('injuries')
    op.drop_index('ix_backtest_results_run_id', table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index('ix_team_stats_team_season', table_name='team_stats')
    op.drop_table('team_stats')
    op.drop_index('ix_standings_team_id', table_name='standings_snapshots')
    op.drop_index('ix_standings_snapshot_date', table_name='standings_snapshots')
    op.drop_index('ix_standings_league_season', table_name='standings_snapshots')
    op.drop_table('standings_snapshots')
    op.drop_index('ix_players_team_id', table_name='players')
    op.drop_index('ix_players_slug', table_name='players')
    op.drop_index('ix_players_name', table_name='players')
    op.drop_table('players')
    op.drop_index('ix_matches_status', table_name='matches')
    op.drop_index('ix_matches_scheduled_at', table_name='matches')
    op.drop_index('ix_matches_league_id', table_name='matches')
    op.drop_index('ix_matches_home_team_id', table_name='matches')
    op.drop_index('ix_matches_external_id', table_name='matches')
    op.drop_index('ix_matches_away_team_id', table_name='matches')
    op.drop_table('matches')
    op.drop_index('ix_teams_slug', table_name='teams')
    op.drop_index('ix_teams_name', table_name='teams')
    op.drop_index('ix_teams_league_id', table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_seasons_start_date', table_name='seasons')
    op.drop_index('ix_seasons_league_id', table_name='seasons')
    op.drop_index('ix_seasons_is_current', table_name='seasons')
    op.drop_index('ix_seasons_end_date', table_name='seasons')
    op.drop_table('seasons')
    op.drop_index('ix_ingestion_errors_run_id', table_name='ingestion_errors')
    op.drop_table('ingestion_errors')
    op.drop_index('ix_generated_reports_job_id', table_name='generated_reports')
    op.drop_table('generated_reports')
    op.drop_index('ix_report_jobs_type', table_name='report_jobs')
    op.drop_index('ix_report_jobs_status', table_name='report_jobs')
    op.drop_table('report_jobs')
    op.drop_index('ix_leagues_sport_id', table_name='leagues')
    op.drop_index('ix_leagues_slug', table_name='leagues')
    op.drop_index('ix_leagues_is_active', table_name='leagues')
    op.drop_index('ix_leagues_country', table_name='leagues')
    op.drop_table('leagues')
    op.drop_index('ix_ingestion_runs_status', table_name='ingestion_runs')
    op.drop_index('ix_ingestion_runs_started', table_name='ingestion_runs')
    op.drop_index('ix_ingestion_runs_source', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index('ix_backtest_runs_status', table_name='backtest_runs')
    op.drop_index('ix_backtest_runs_model_version', table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_sports_slug', table_name='sports')
    op.drop_index('ix_sports_name', table_name='sports')
    op.drop_index('ix_sports_is_active', table_name='sports')
    op.drop_table('sports')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_feature_snapshots_prediction_id'), table_name='feature_snapshots')
    op.drop_table('feature_snapshots')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
