/**
 * Frontend pick-tier classifier.
 *
 * Mirrors backend/app/core/tier_system.py::pick_tier_expression() so the
 * Predictions Explorer and Fixture lists can render tier-badges per row
 * without needing a new backend field on every fixture response.
 *
 * Source of truth: backend/app/core/tier_leagues.py (auto-generated by
 * scripts/bootstrap_tier_league_ids.py). When that regenerates, update
 * the UUID sets below too.
 */
import type { PickTierSlug } from "@/types/api";

// ─── Confidence thresholds (must match backend CONF_THRESHOLD) ──────────────
export const PICK_TIER_CONF_THRESHOLD: Record<PickTierSlug, number> = {
  platinum: 0.75,
  gold: 0.7,
  silver: 0.65,
  free: 0.55,
};

// ─── League UUID whitelists ─────────────────────────────────────────────────
// Cumulative by design: GOLD ⊇ PLATINUM, SILVER ⊇ GOLD.
const LEAGUES_PLATINUM = new Set<string>([
  "e0efa138-7f03-4c60-bcbc-c463f3842438", // Champions League
  "137edd72-3ef0-4e4a-9708-63c30df6ce1e", // Süper Lig
  "f2b51cb0-733d-4f79-863f-cd510fd17311", // Eredivisie
  "dc5763a2-0da9-4a13-8d6c-1c0ce6b2cc4c", // Premier League
  "449aa2d2-74e9-4cfb-a32a-efea876d54b9", // Saudi Pro League
]);

const LEAGUES_GOLD = new Set<string>([
  ...Array.from(LEAGUES_PLATINUM),
  "f71b7c32-9f4a-41d6-b5ad-8a28b670f2bc", // Scottish Premiership
  "81998369-31b7-4d92-9b63-4d071190c9c5", // Liga MX
  "38fa627e-169e-4631-a646-ff6649ed5864", // Chinese Super League
  "c14d2d79-979f-4ddb-b8b5-8195725fe121", // Primeira Liga
  "c12726e4-bc51-45b8-9cc7-685d958c30f5", // Bundesliga
]);

const LEAGUES_SILVER = new Set<string>([
  ...Array.from(LEAGUES_GOLD),
  "43106ec3-111e-4a37-a415-9e0b20bd3590", // Jupiler Pro League
  "4acd5222-802e-454e-b415-e9c1af26961d", // Championship
  "00cdab5a-7846-4a6c-96d2-62d5ed12e305", // La Liga
  "26d8d924-e0dd-4251-81da-82c7a0a6dce9", // Serie A
]);

// ─── Fallback: classify by league NAME when ID is not available ─────────────
// Many fixture responses include league_name but not league_id (external
// data-source IDs). We fall back to a name-match set. Names are the display
// names as seen in the DB/API.
const NAMES_PLATINUM = new Set<string>([
  "Champions League",
  "UEFA Champions League",
  "Süper Lig",
  "Super Lig",
  "Eredivisie",
  "Premier League",
  "Saudi Pro League",
]);
const NAMES_GOLD = new Set<string>([
  ...Array.from(NAMES_PLATINUM),
  "Scottish Premiership",
  "Liga MX",
  "Chinese Super League",
  "Primeira Liga",
  "Bundesliga",
]);
const NAMES_SILVER = new Set<string>([
  ...Array.from(NAMES_GOLD),
  "Jupiler Pro League",
  "Championship",
  "La Liga",
  "Serie A",
]);

/**
 * Classify a pick into its tier. Returns null when the prediction has no
 * confidence (e.g. fixture without a forecast yet).
 *
 * Precedence: ID match > name match > free.
 */
export function classifyPickTier(
  opts: {
    leagueId?: string | null;
    leagueName?: string | null;
    confidence?: number | null;
  },
): PickTierSlug | null {
  const conf = opts.confidence;
  if (conf == null) return null;
  if (conf < PICK_TIER_CONF_THRESHOLD.free) return null; // below 0.55 → no tier

  const id = opts.leagueId ?? "";
  const name = opts.leagueName ?? "";

  const inPlat = (id && LEAGUES_PLATINUM.has(id)) || NAMES_PLATINUM.has(name);
  const inGold = (id && LEAGUES_GOLD.has(id)) || NAMES_GOLD.has(name);
  const inSilver = (id && LEAGUES_SILVER.has(id)) || NAMES_SILVER.has(name);

  if (inPlat && conf >= PICK_TIER_CONF_THRESHOLD.platinum) return "platinum";
  if (inGold && conf >= PICK_TIER_CONF_THRESHOLD.gold) return "gold";
  if (inSilver && conf >= PICK_TIER_CONF_THRESHOLD.silver) return "silver";
  return "free";
}

/**
 * PickTier order (low → high) for filter logic. `TIER_RANK.platinum === 3`
 * means "platinum is the highest tier".
 */
export const TIER_RANK: Record<PickTierSlug, number> = {
  free: 0,
  silver: 1,
  gold: 2,
  platinum: 3,
};
